woowacourse-teams/2023-festa-go

.github/workflows/closed-pr-notification.yml
.github/workflows/opened-pr-notification.yml

- closed: #17  
dev 브랜치로 PR 요청, 병합 시 슬랙에 알림을 보내는 기능 추가
GIthub Actions를 사용하여 PR이 생성되거나, 병합이 되면 슬랙에 알림을 보내는 기능을 추가

[ALL] FEAT: dev 브랜치로 PR 요청, 병합 시 슬랙에 알림을 보낸다. (#17)

---

android/festago-staff/app/src/main/java/com/festago/festagostaff/data/dto/TicketValidationRequestDto.kt
android/festago-staff/app/src/main/java/com/festago/festagostaff/data/repository/TicketDefaultRepository.kt
android/festago-staff/app/src/main/java/com/festago/festagostaff/data/service/TicketRetrofitService.kt
android/festago-staff/app/src/main/java/com/festago/festagostaff/presentation/ui/ticketvalidation/TicketValidationActivity.kt
android/festago-staff/app/src/main/java/com/festago/festagostaff/presentation/ui/ticketvalidation/TicketValidationViewModel.kt
android/festago-staff/app/src/main/res/drawable/btn_circle_primary.xml
android/festago-staff/app/src/main/res/drawable/ic_refresh.xml
android/festago-staff/app/src/main/res/layout/activity_ticket_validation.xml
android/festago-staff/app/src/test/java/com/festago/festagostaff/presentation/ui/ticketvalidation/TicketValidationViewModelTest.kt

- closed: #63 
- QR을 연속적으로 스캔할 수 있도록 수정
- 별도 화면에서 스캔하지않고, ScanValidationActivity 내에서 스캔 및 결과 확인할 수 있도록 수정
- 직전에 인식했던 QR 코드가 또 인식되면 코드 검증 요청을 보내지 않도록 함

[AN/STAFF] feat: QR 스캔 화면 커스텀 및 기능을 변경(#63)

---

android/festago/app/src/main/AndroidManifest.xml
android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainViewModel.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeItemType.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
android/festago/app/src/main/res/drawable/ic_bottom_navigation_festival.xml
android/festago/app/src/main/res/drawable/ic_bottom_navigation_user.xml
android/festago/app/src/main/res/layout/activity_home.xml
android/festago/app/src/main/res/layout/fragment_festival_list.xml
android/festago/app/src/main/res/layout/fragment_my_page.xml
android/festago/app/src/main/res/layout/fragment_ticket_list.xml
android/festago/app/src/main/res/menu/menu_bottom_navigation.xml
android/festago/app/src/main/res/values/strings.xml

- closed: #92 
- HomeActivity에서 바텀네비게이션으로 화면을 이동하도록 구현했습니다.
- FestivalListFragment / TicketListFragment / MyPageFramgent 로 이동합니다.
- 프래그먼트는 show / hide로 변경됩니다. 
- 디자인 작업 없이 빈 화면으로 이동하도록 구현했습니다.
- 앱 실행 시 HomeActivity로 launch 되도록 했습니다.

[AN/USER]  feat: 메인 화면을 프래그먼트, 바텀네비게이션 구현(#92)

---

android/festago/app/src/main/AndroidManifest.xml
android/festago/app/src/main/java/com/festago/festago/data/repository/FestivalDefaultRepository.kt
android/festago/app/src/main/java/com/festago/festago/domain/model/Festival.kt
android/festago/app/src/main/java/com/festago/festago/domain/repository/FestivalRepository.kt
android/festago/app/src/main/java/com/festago/festago/presentation/mapper/FestivalMapper.kt
android/festago/app/src/main/java/com/festago/festago/presentation/model/FestivalUiModel.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/BindingAdapter.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalItemViewHolder.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListAdapter.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListBindingAdapter.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListUiState.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
android/festago/app/src/main/res/drawable/ic_image_placeholder.xml
android/festago/app/src/main/res/layout/fragment_festival_list.xml
android/festago/app/src/main/res/layout/item_festival.xml
android/festago/app/src/main/res/values/strings.xml
android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModelTest.kt

- closed: #95 
- 축제 목록 화면 구현했습니다.
- 리포지토리에서 목 데이터 리턴하도록 했습니다. (로딩 상태를 확인할 수 있도록 delay()가 있습니다)
- 이미지에 사용되는 바인딩어댑터 추가했습니다(Glide). 이미지 바인딩할 때 사용해주세요.
- "진행중/지난축제" 칩은 아직 기획적으로 확정된 부분이 아니라서 임시로 구현했습니다.

[AN/USER] feat: 축제 목록 화면 구현(#95)

---

backend/src/main/java/com/festago/application/StageService.java
backend/src/main/java/com/festago/dto/StageCreateRequest.java
backend/src/main/java/com/festago/exception/ErrorCode.java
backend/src/main/java/com/festago/presentation/AdminController.java
backend/src/test/java/com/festago/application/ApplicationTest.java
backend/src/test/java/com/festago/application/FestivalServiceTest.java
backend/src/test/java/com/festago/application/StageServiceTest.java
backend/src/test/java/com/festago/presentation/AdminControllerTest.java

[BE] feat: 관리자 공연 등록 구현(#116)

---

backend/src/main/java/com/festago/application/TicketService.java
backend/src/main/java/com/festago/domain/Ticket.java
backend/src/main/java/com/festago/dto/TicketCreateRequest.java
backend/src/main/java/com/festago/dto/TicketResponse.java
backend/src/main/java/com/festago/exception/ErrorCode.java
backend/src/main/java/com/festago/presentation/AdminController.java
backend/src/test/java/com/festago/application/EntryServiceTest.java
backend/src/test/java/com/festago/application/TicketServiceTest.java
backend/src/test/java/com/festago/domain/TicketTest.java
backend/src/test/java/com/festago/presentation/AdminControllerTest.java
backend/src/test/java/com/festago/presentation/TicketControllerTest.java
backend/src/test/java/com/festago/support/TicketFixture.java

[BE] feat: 관리자 티켓 발급 구현(#117) 

---

backend/src/main/java/com/festago/application/FestivalService.java
backend/src/main/java/com/festago/dto/FestivalsResponse.java
backend/src/main/java/com/festago/presentation/FestivalController.java
backend/src/test/java/com/festago/application/FestivalServiceTest.java
backend/src/test/java/com/festago/presentation/FestivalControllerTest.java

- closed: #123 
기존의 FestivalServiceTest가 SpringBootTest인데, 이를 Mock기반 단위테스트로 수정하였습니다.
그에 따라 기존의 테스트 코드가 실패되어 주석처리했습니다.
이는 #139 이슈에서 처리되면 될 것 같습니다.

[BE] feat: 축제 전체 조회 API 구현 (#123)

---

backend/src/main/java/com/festago/application/TicketService.java
backend/src/main/java/com/festago/domain/Ticket.java

- closed: #151 
orElse() 사용 시, 값이 없더라도 해당 메소드를 호출하므로 중복된 데이터가 생성됩니다.
따라서 orElseGet()을 사용하여 값이 없을때만 새로운 Ticket을 영속하도록 수정했습니다.

[BE] feat: 티켓을 생성할 때 데이터베이스에 INSERT 되지 않는 버그 수정 (#151)

---

backend/src/main/java/com/festago/application/FestivalService.java
backend/src/main/java/com/festago/domain/Festival.java
backend/src/main/java/com/festago/domain/Stage.java
backend/src/main/java/com/festago/domain/StageRepository.java
backend/src/main/java/com/festago/domain/TicketAmount.java
backend/src/main/java/com/festago/dto/FestivalDetailResponse.java
backend/src/main/java/com/festago/dto/FestivalDetailStageResponse.java
backend/src/main/java/com/festago/dto/FestivalDetailTicketResponse.java
backend/src/main/java/com/festago/presentation/FestivalController.java
backend/src/test/java/com/festago/application/FestivalServiceTest.java
backend/src/test/java/com/festago/application/integration/FestivalServiceIntegrationTest.java
backend/src/test/java/com/festago/presentation/FestivalControllerTest.java

- closed: #119 
무대 정보는 무대 시작 시간 기준으로 정렬되도록 했습니다.
조회시 편의를 위해 Stage에 `@OneToMany List<Ticket>`를 추가했습니다.
(OneToMany관계를 걸지 않으면, for문을 돌면서 복잡한 연산을 수행해야하고, 이에 따라 DTO로 변환하는 과정이 상당히 복잡해집니다.)

[BE] feat: 축제 상세 정보 조회 Api 구현(#119)

---

backend/src/main/java/com/festago/application/MemberTicketService.java
backend/src/main/java/com/festago/domain/MemberTicket.java
backend/src/main/java/com/festago/dto/CurrentFestivalResponse.java
backend/src/main/java/com/festago/dto/CurrentMemberTicketResponse.java
backend/src/main/java/com/festago/dto/CurrentMemberTicketsResponse.java
backend/src/main/java/com/festago/dto/CurrentStageResponse.java
backend/src/main/java/com/festago/dto/MemberTicketResponse.java
backend/src/main/java/com/festago/dto/MemberTicketsResponse.java
backend/src/main/java/com/festago/presentation/MemberTicketController.java
backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
backend/src/test/java/com/festago/domain/MemberTicketTest.java
backend/src/test/java/com/festago/presentation/MemberTicketControllerTest.java

- closed: #79 
- 티켓은 입장시간 12시간 이전부터 노출됩니다.
- 티켓은 입장시간 24시간 이후까지 노출됩니다.
- 티켓은 (활성화) -> (비활성화) 순으로 정렬됩니다.
- (활성화) 및 (비활성화) 내에서는 입장시간이 현재 시간과 가까운 순으로 정렬됩니다.
```
현재시간) 5시
[활성화] 4시 입장
[활성화] 3시 입장
[비활성화] 6시 입장
[비활성화] 7시 입장
```
<br>
- 티켓은 무대 시작시간이 최신순으로 정렬됩니다.
---
226db9a5d072e809ddbdd7dbf0c2231f6518b7d8 해당 커밋에서 기존에 Map으로 반환하던 메서드를 List를 반환하도록 수정했습니다.
[전자] stream도는 횟수가 적습니다. 하지만 가독성이 좋지 않습니다.
[후자] stream을 2번 더 돕니다. 하지만 가독성이 좋습니다.
한 멤버의 현재 활성화된 티켓 개수(`currentMemberTickets`) 사이즈가 크지 않아, stream을 2번 더 돈다고 큰 성능상의 차이가 없기에 가독성을 챙기는게 좋을 것 같다는 @BGuga 의 의견을 반영했습니다!
해당 부분 코드리뷰 부탁드립니다 🙇🏻‍♀️

[BE] feat: 티켓 목록 조회 API와 예매 목록 조회 API 분리 (#79)

---

android/festago/app/build.gradle.kts
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
android/festago/app/src/main/res/layout/activity_ticket_reserve.xml

- closed: #222
- swipe 라이브러리추가
- 축제 예매 화면 새로고침 기능 추가
[Screen_recording_20230803_193449.webm](https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/c0af71b4-db7d-46c5-bb7d-b361447bea1e)

[AN/USER] 축제 예매 화면 새로고침 기능 (#222)

---

android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveViewHolder.kt
android/festago/app/src/main/res/layout/item_ticket_reserve.xml
android/festago/app/src/main/res/values/strings.xml

- closed: #220
- 기존 xml 티켓 오픈 예정 textView 삭제
- 예매 버튼 시간에 따라서 활성상태 변경

[AN/USER] 축제 예매 화면 오픈시간 전에 버튼 비활성화 (#220)

---

android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
android/festago/app/src/main/res/layout/fragment_festival_list.xml

- closed: #228
[Screen_recording_20230803_201034.webm](https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/16573ff8-7ba7-4cdf-962a-06e5b363574f)
- 축제 목록 화면 새로고침 기능 추가

[AN/USER] 페스티벌 축제 화면 새로고침 기능 추가 (#228)

---

backend/src/main/resources/logback-spring.xml
backend/src/main/resources/logs/common/file-error-appender.xml
backend/src/main/resources/logs/common/file-info-appender.xml
backend/src/main/resources/logs/common/file-warn-appender.xml
backend/src/main/resources/logs/error/file-error-appender.xml
backend/src/main/resources/logs/error/file-info-appender.xml
backend/src/main/resources/logs/error/file-warn-appender.xml

- closed: #236 
기존 Appender 의 경로가 
위와 같이 설정되어 있을 때 
```
nohup java -jar -Duser.timezone=Asia/Seoul festa-go-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev 
```
해당 명령어를 실행 했을 때 Appender 를 찾지 못합니다.
반면 Intellij 에서 Run Application 을 실행했을 때는 Appender 를 발견합니다.
그래서 appender 파일 경로를 
로 바꾸어 주니 log 파일이 
```
backend/build/libs/log/{fileName}
```
로 저장 되어서 해당 저장 경로를 홈 디렉토리에 저장하도록 변경하였습니다.

[BE] chore: Appender 상대 경로, 로그 저장 위치 변경 (#236)

---

backend/src/main/java/com/festago/domain/Member.java
backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
backend/src/test/java/com/festago/auth/application/integration/AuthServiceIntegrationTest.java
backend/src/test/java/com/festago/domain/MemberRepositoryTest.java
backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
backend/src/test/java/com/festago/support/DatabaseCleaner.java
backend/src/test/java/com/festago/support/DatabaseClearExtension.java
backend/src/test/resources/application-test.yml

- closed: #268 
회원이 탈퇴할 때, 데이터베이스에서 삭제되는 것이 아니라, soft delete 처리를 하였습니다.
API는 추후 #267 이슈가 머지되면, MemberController에서 구현해야 할 듯 합니다.

[BE] feat: 회원 soft delete 탈퇴 기능 구현 (#268)

---

backend/src/main/java/com/festago/auth/presentation/AuthController.java
backend/src/test/java/com/festago/auth/presentation/AuthControllerTest.java

- closed: #291
기존 kakao oauth2 redirect용으로 열어두었던 GET /auth/oauth2/kakao?code=${code} API를 삭제했습니다.

[BE] refactor: 불필요한 oauth2 redirect용 API 삭제 (#291)

---

backend/src/main/java/com/festago/application/MemberTicketService.java
backend/src/main/java/com/festago/domain/MemberTicket.java
backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
backend/src/test/java/com/festago/domain/MemberTicketTest.java

- closed: #265 
티켓 목록 API에서 기존에 입장시간이 12시간 남은 티켓들만 노출이되었는데, 이제 입장 시간 이전의 티켓은 모두 활성화되도록 수정하였습니다.

[BE] refactor: 티켓 목록 API에서 입장 시간 이전 티켓 모두 활성화되도록 수정 (#265)

---

backend/src/main/java/com/festago/auth/infrastructure/FestagoOAuth2Client.java
backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2UserInfoErrorHandler.java
backend/src/main/java/com/festago/exception/ErrorCode.java
backend/src/test/java/com/festago/auth/infrastructure/KakaoOAuth2UserInfoClientTest.java

[BE] refactor: Oauth2 카카오 서버의 4xx에러 발생할 경우 BadRequestException으로 수정 (#296)

---

backend/src/main/java/com/festago/auth/dto/KakaoUserInfo.java

- closed: #301 
카카오톡 OAuth 로그인 시, 프로필 이미지를 선택적으로 제공할 수 있습니다.
또한, 기본 프로필인 경우 이미지가 null 값으로 들어오게 됩니다.
따라서 프로필 이미지가 null인 경우, 기본 이미지 URL을 추가했습니다.
해당 부분을 지금처럼 DTO에서 기본 값을 설정할 지, 서비스, 도메인에서 할지 논의가 필요해 보입니다.

[BE] feat: profileImage 기본값 추가 (#301)

---

android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservationStageMapper.kt
android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketReserveItemUiModel.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveEvent.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveUiState.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/adapter/TicketReserveAdapter.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveViewHolder.kt
android/festago/app/src/main/res/layout/item_ticket_reserve.xml
android/festago/app/src/main/res/values/strings.xml
android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt

- closed: #315 
- 로그인하지 않았다면 버튼을 "로그인 후 예매"로 변경
- "로그인 후 예매" 클릭 시 로그인 화면으로 이동

[AN/USER] feat: 공연 목록 화면에서 로그인하지 않은 경우 처리(#315)

---

backend/src/main/java/com/festago/auth/dto/KakaoUserInfo.java
backend/src/main/java/com/festago/domain/Member.java
backend/src/test/java/com/festago/domain/MemberTest.java

- closed: #358 
Member 주 생성자에서 null 값을 체크하여 null이면 기본값을 할당하도록 변경하였습니다.

[BE] fix: 회원 가입시 프로필 사진을 권한을 주지 않으면 null로 저장되는 문제를 해결 (#358)

---

android/festago/app/src/main/res/xml/backup_rules.xml
android/festago/app/src/main/res/xml/data_extraction_rules.xml

- closed: #379
오류 발생 과정
로그인 -> EncryptedSharedPreference 에 토큰 저장-> 앱 삭제 -> 재설치 -> 토큰 저장소 접근
Crashlytics 에서 원인 분석
Caused by android.security.KeyStoreException Signature/MAC verification failed
구글링 결과
https://github.com/google/tink/issues/535#issuecomment-912170221
https://github.com/google/tink/issues/535#issuecomment-1266799661
공식 문서
https://developer.android.com/guide/topics/data/autobackup#IncludingFiles
문제 인식
sharedPreference 가 default 로 backup 되는데 EncryptedSharedPreference 를 다시 불러올 때 암호화 할 때 사용한 키가 유효하지 않음.
해결 방법
allowBackup = “false” -> 문제는 데이터 백업 안됨 패스
try catch 로 잡고 EncryptedSharedPreference 재설정
EncryptedSharedPreference 가 Auto Backup 되지 않도록 제외

[AN/USER] fix: 재설치 크래시 버그 수정(#379)

---

backend/src/main/java/com/festago/application/EntryService.java
backend/src/main/java/com/festago/application/MemberTicketService.java
backend/src/test/java/com/festago/application/EntryServiceTest.java
backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
backend/src/test/java/com/festago/support/TimeInstantProvider.java

[BE] refactor: LocalDateTime.now() 사용을 LocalDateTime.now(clock) 형식으로 변경 (#395)

---

backend/src/main/java/com/festago/application/StudentService.java
backend/src/main/java/com/festago/domain/School.java
backend/src/main/java/com/festago/domain/Student.java
backend/src/main/java/com/festago/domain/StudentCode.java
backend/src/main/java/com/festago/domain/StudentCodeRepository.java
backend/src/main/java/com/festago/dto/StudentVerificateRequest.java
backend/src/main/java/com/festago/exception/ErrorCode.java
backend/src/main/java/com/festago/presentation/StudentController.java
backend/src/main/resources/db/migration/V2__student_code_add_username.sql
backend/src/test/java/com/festago/application/StudentServiceTest.java
backend/src/test/java/com/festago/presentation/StudentControllerTest.java

- closed: #430 
1. 학생 인증 기능을 추가하였습니다.
2. 기존 코드 변경 사항
학생 인증 완료후 Student 객체를 생성할 때 메일 요청시 요청했던, username이 필요합니다.
(ohs@knu.ac.kr에서 @ 앞부분이 username )
그런데 저희는 username을 어느 곳에서도 저장하지 않아서, Student 객체에 username을 넣어주지 못합니다.
따라서 메일 인증 요청때 생성하던 StudentCode 객체에 username 필드를 추가하였습니다.

[BE] feat: 이메일 코드를 통한 학생 인증 기능을 추가 (#430)

---

backend/src/main/java/com/festago/application/SchoolService.java
backend/src/main/java/com/festago/dto/SchoolResponse.java
backend/src/main/java/com/festago/dto/SchoolsResponse.java
backend/src/main/java/com/festago/presentation/SchoolController.java
backend/src/test/java/com/festago/presentation/SchoolControllerTest.java

- closed: #431 
학생 인증을 위한 학교 목록 조회 기능을 구현했습니다.

[BE] feat: 학교 목록 조회 기능 구현 (#431)

---

backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java

[BE] feat: WARN 로그 스택 트레이스 출력 제거 (#437)

---

backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java

[BE] feat: InvalidMediaTypeException 예외 핸들링 (#439)

---

backend/src/main/java/com/festago/festival/domain/Festival.java
backend/src/main/java/com/festago/ticket/domain/Ticket.java
backend/src/main/resources/db/migration/V4__add_school_fk.sql

[BE] refactor: Ticket의 school not null 제약조건 제거

---

android/festago/app/src/main/AndroidManifest.xml
android/festago/app/src/main/java/com/festago/festago/data/di/ViewModelScopeModule.kt
android/festago/app/src/main/java/com/festago/festago/data/di/singletonscope/RepositoryModule.kt
android/festago/app/src/main/java/com/festago/festago/data/di/singletonscope/ServiceModule.kt
android/festago/app/src/main/java/com/festago/festago/data/dto/SchoolResponse.kt
android/festago/app/src/main/java/com/festago/festago/data/dto/SchoolsResponse.kt
android/festago/app/src/main/java/com/festago/festago/data/repository/SchoolDefaultRepository.kt
android/festago/app/src/main/java/com/festago/festago/data/service/SchoolRetrofitService.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SchoolUiState.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolActivity.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolEvent.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolUiState.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolViewModel.kt
android/festago/app/src/main/res/layout/activity_select_school.xml
android/festago/app/src/main/res/layout/item_select_school.xml
android/festago/app/src/main/res/values/strings.xml
android/festago/app/src/test/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolViewModelTest.kt
android/festago/domain/src/main/java/com/festago/festago/model/School.kt
android/festago/domain/src/main/java/com/festago/festago/repository/SchoolRepository.kt

[AN/USER] feat: 학교 선택 화면 구현(#374)

---

android/festago/app/src/main/java/com/festago/festago/data/dto/SendVerificationRequest.kt
android/festago/app/src/main/java/com/festago/festago/data/dto/VerificationRequest.kt
android/festago/app/src/main/java/com/festago/festago/data/repository/StudentVerificationDefaultRepository.kt
android/festago/app/src/main/java/com/festago/festago/data/service/StudentVerificationRetrofitService.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationActivity.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationEvent.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationViewModel.kt
android/festago/app/src/main/res/layout/activity_student_verification.xml
android/festago/app/src/test/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationViewModelTest.kt

- closed: #456 
학생 인증 연동 완료
이벤트 처리 완료
이메일 전송 실패 -> 이메일 확인 요청 이벤트 발생
타임 아웃 -> 시간 초과 이벤트 발생
인증 실패 -> 인증 실패 이벤트
인증 성공 -> 모든 액티비티 종료 후 메인 재시작

[AN/USER] feat: 학생 인증 API 연동(#456) 

---

backend/src/test/java/com/festago/acceptance/steps/ExampleStep.java
backend/src/test/java/com/festago/acceptance/steps/ExampleStep2.java
backend/src/test/resources/features/example.feature

- closed: #487 
축제를 생성하기 위해서는 학교가 존재해야합니다.
축제 생성 테스트에 학교 생성 과정을 추가했습니다

[BE] feat: Cucumber 테스트 수정(#487)

---

backend/src/main/java/com/festago/auth/application/AuthService.java

- closed: #479
불필요한 메서드 분리를 제거함으로써, 사용되지 않는 public 메서드를 없앴습니다.

[BE] refactor: 불필요한 메서드 분리 제거 (#479)

---

backend/src/test/java/com/festago/application/EntryServiceTest.java
backend/src/test/java/com/festago/application/FestivalServiceTest.java
backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
backend/src/test/java/com/festago/application/StudentServiceTest.java
backend/src/test/java/com/festago/application/integration/StageServiceIntegrationTest.java
backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
backend/src/test/java/com/festago/application/integration/TicketingServiceIntegrationTest.java
backend/src/test/java/com/festago/auth/application/AdminAuthServiceTest.java
backend/src/test/java/com/festago/auth/application/AuthServiceTest.java
backend/src/test/java/com/festago/auth/domain/OAuth2ClientsTest.java
backend/src/test/java/com/festago/auth/infrastructure/HeaderTokenExtractorTest.java
backend/src/test/java/com/festago/auth/infrastructure/JwtAuthExtractorTest.java
backend/src/test/java/com/festago/auth/infrastructure/KakaoOAuth2UserInfoClientTest.java
backend/src/test/java/com/festago/auth/presentation/RoleArgumentResolverTest.java
backend/src/test/java/com/festago/domain/EntryCodeTest.java
backend/src/test/java/com/festago/domain/EntryStateTest.java
backend/src/test/java/com/festago/domain/FestivalTest.java
backend/src/test/java/com/festago/domain/StageTest.java
backend/src/test/java/com/festago/domain/TicketAmountTest.java
backend/src/test/java/com/festago/domain/TicketEntryTimeTest.java
backend/src/test/java/com/festago/domain/TicketTest.java
backend/src/test/java/com/festago/infrastructure/JwtEntryCodeExtractorTest.java
backend/src/test/java/com/festago/infrastructure/JwtEntryCodeProviderTest.java
backend/src/test/java/com/festago/ticketing/application/TicketingServiceTest.java

[BE] refactor: assertThatThrownBy.hasMessage()에서 ErrorCode를 활용하도록 수정 (#476)

---

backend/src/main/java/com/festago/festival/domain/Festival.java
backend/src/main/java/com/festago/ticket/domain/Ticket.java
backend/src/main/resources/db/migration/V6__school_notnull.sql

- closed: #468 
🚨 merge 전 dev DB의 데이터에서 정합성이 맞지 않는 데이터가 있는지 확인해야합니다.

[BE] feat: Festival, Ticket 테이블의 school_id의 not null 제약조건 추가(#468)

---

backend/src/main/java/com/festago/auth/dto/AdminLoginRequest.java
backend/src/main/java/com/festago/auth/dto/AdminSignupRequest.java
backend/src/main/java/com/festago/auth/dto/LoginRequest.java
backend/src/main/java/com/festago/auth/dto/RootAdminInitializeRequest.java
backend/src/main/java/com/festago/common/exception/dto/ErrorResponse.java
backend/src/main/java/com/festago/entry/dto/TicketValidationRequest.java
backend/src/main/java/com/festago/festival/dto/FestivalCreateRequest.java
backend/src/main/java/com/festago/presentation/AuthController.java
backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
backend/src/main/java/com/festago/presentation/StudentController.java
backend/src/main/java/com/festago/school/dto/SchoolCreateRequest.java
backend/src/main/java/com/festago/stage/dto/StageCreateRequest.java
backend/src/main/java/com/festago/student/dto/StudentSendMailRequest.java
backend/src/main/java/com/festago/student/dto/StudentVerificateRequest.java
backend/src/main/java/com/festago/ticket/dto/TicketCreateRequest.java
backend/src/main/java/com/festago/ticketing/dto/TicketingRequest.java

[BE] refactor: request DTO Validation 추가(#462)

---

android/festago/app/src/main/java/com/festago/festago/data/dto/FestivalResponse.kt
android/festago/app/src/main/java/com/festago/festago/data/dto/ReservationFestivalResponse.kt
android/festago/app/src/test/java/com/festago/festago/data/repository/ReservationTicketRetrofitServiceTest.kt

- closed: #507 
- dto에 schoolId 추가했습니다. 
- 이제 축제 목록, 축제 상세 정상 조회됩니다.
- 아직 어디에 필요한지 결정되지 않아 도메인 모델에는 반영하지 않았습니다. (아마 재학생 여부 확인에 사용할듯?)

[AN/USER] feat: 축제 목록, 축제 상세 API 변경사항 반영

---

android/festago/app/src/main/java/com/festago/festago/data/repository/AuthDefaultRepository.kt
android/festago/app/src/main/java/com/festago/festago/data/repository/FestivalDefaultRepository.kt
android/festago/app/src/main/java/com/festago/festago/data/repository/ReservationTicketDefaultRepository.kt
android/festago/app/src/main/java/com/festago/festago/data/repository/SchoolDefaultRepository.kt
android/festago/app/src/main/java/com/festago/festago/data/repository/StudentVerificationDefaultRepository.kt
android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
android/festago/app/src/main/java/com/festago/festago/data/repository/TokenDefaultRepository.kt
android/festago/app/src/main/java/com/festago/festago/data/repository/UserDefaultRepository.kt
android/festago/app/src/main/java/com/festago/festago/data/util/ResponseExt.kt
android/festago/app/src/main/java/com/festago/festago/data/util/ResultExt.kt

- closed: #509
- Json convert시 생기는 에러 처리를 위한 새로운 함수 생성
- runCatchingResponse
- onSuccessOrCatch
- 모든 Repository 해당 함수를 사용하도록 리팩토링

[AN/USER] Json convert시 생긴 에러 Catch 하도록 수정 (#509)

---

android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
android/festago/app/src/test/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewModelTest.kt
android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt

- closed: #497 
테스트 코드에서 given 절을 함수로 분리

[AN/USER] 테스트 코드 리팩터링 (티켓 목록, 티켓 예매, 티켓 기록, 홈화면) (#497)

---

android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt

- closed: #514 
- uiState 값이 변경되지 않았을 때 collect가 발생하지 않아 무한 로딩하는 버그 수정했습니다.
- 축제 목록, 마이페이지, 티켓 목록, 축제 상세 화면

[AN/USER] fix: SwipeRefresh 무한 로딩 버그 수정 (#514)

---

android/festago/app/src/main/java/com/festago/festago/presentation/service/TicketEntryService.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt

- closed: #519 
- 새로고침 시 타이머가 작동하지 않는 문제 해결
- 입장 처리시 여러번 토스트가 띄워지는 문제 해결

[AN/USER] 티켓 제시 화면 2개 버그 해결 (#519)

---

backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
backend/src/main/java/com/festago/student/infrastructure/MockMailClient.java

- closed: #542
```java
@Component
@Profile("!{dev|prod}")
public class MockMailClient implements MailClient {
...
}
```
스프링 5.1 이상 부터 정규식을 통해 프로파일을 설정할 수 있다고 하네요.
따라서 정규식을 사용하여 `dev` 또는 `prod` 프로파일이 아니면 해당 빈을 등록하도록 하였습니다.

[BE] fix: MockMailClient 빈으로 등록되는 프로파일 변경 (#542)

---

android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeEvent.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeViewModel.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInEvent.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInViewModel.kt
android/festago/app/src/main/res/layout/activity_sign_in.xml
android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
android/festago/app/src/test/java/com/festago/festago/presentation/ui/signin/SignInViewModelTest.kt

- closed: #534 
홈화면에서 회전에도 이전에 선택한 화면을 기억
티켓 리스트, 마이페이지 로그인하지 않았을 경우 이벤트 발생
마이페이지 ScrollView 적용 필요

[AN/USER] 홈 화면 회전시 이전에 선택한 화면을 그대로 보여준다. (#534)

---

backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
backend/src/main/java/com/festago/fcm/config/FCMConfig.java
backend/src/main/java/com/festago/student/infrastructure/GoogleMailClient.java
backend/src/main/java/com/festago/student/infrastructure/MockMailClient.java

- closed: #551 
```java
@Component
@Profile("!dev & !prod")
public class MockMailClient implements MailClient {
private static final Logger log = LoggerFactory.getLogger(MockMailClient.class);
@Override
public void send(String message) {
}
@PostConstruct
public void post() {
log.info("Mock Mail Init!");
}
}
```
```java
@Component
@Profile("dev | prod")
public class RealMailClient implements MailClient {
private static final Logger log = LoggerFactory.getLogger(RealMailClient.class);
@Override
public void send(String message) {
}
@PostConstruct
public void post() {
log.info("Real Mail Init!");
}
}
```
다음과 같이 프로파일 설정 후 테스트 결과 
`MockMailClient`는 dev 또는 prod 프로파일이 아닐 때 등록이 확인되었고,
`RealMailClient`는 dev 또는 prod 프로파일 일 때 등록이 확인되었습니다.

[BE] fix: 컴포넌트 스캔 대상이 되는 빈의 @Profile 설정 수정 (#551)

---

android/festago/app/src/main/res/layout/fragment_my_page.xml
android/festago/app/src/main/res/layout/item_ticket_history.xml

- closed: #547 
- closed: #524 
- 마이페이지 스크롤 적용 완료
- 레이아웃 장풍 구조 리팩했습니다. (아래 캡쳐 참고)
- 마이페이지, ticket history 다크모드 적용했습니다.

[AN/USER] refactor: 마이페이지 스크롤 적용, 레이아웃 리팩터링, 다크모드 적용(#547)

---

backend/src/main/java/com/festago/entry/dto/event/EntryProcessEvent.java
backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
backend/src/main/java/com/festago/fcm/domain/FCMChannel.java

- closed: #565
우선 작동을 위해 `ENTRY_PROCESS`를 하드코딩 하였습니다.
추후 #483 이슈가 처리되면 개선이 필요할 것 같습니다.

[BE] FCMNotificationEventListener의 FCMChannel을 수정 (#565)

---

backend/src/main/java/com/festago/presentation/StudentController.java
backend/src/main/java/com/festago/student/application/StudentService.java
backend/src/main/java/com/festago/student/dto/StudentResponse.java
backend/src/main/java/com/festago/student/dto/StudentSchoolResponse.java
backend/src/main/java/com/festago/student/repository/StudentRepository.java
backend/src/test/java/com/festago/presentation/StudentControllerTest.java
backend/src/test/java/com/festago/student/application/StudentServiceTest.java
backend/src/test/java/com/festago/student/repository/StudentRepositoryTest.java
backend/src/test/java/com/festago/support/StudentFixture.java

- closed: #496 
마이페이지 및 티케팅시 필요한 회원의 학생 인증 정보 조회 API를 구현하였습니다!

[BE] feat: 회원의 학생 인증 정보 조회 API 구현 (#496)

---

android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveEvent.kt
android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
android/festago/app/src/main/res/values/strings.xml
android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
android/festago/domain/src/main/java/com/festago/festago/model/ErrorCode.kt

[AN/USER] feat: 예매 실패 케이스 처리(#369)

---

android/festago/app/src/main/res/layout/fragment_festival_list.xml

- closed: #614 
홈 화면 UX 개선 완료했습니다.
Coordinator layout 을 사용했습니다.
CollapsiongToolbarLayout 의 collapseMode 를 pin 으로 하고 RecyclerView 에 behavior 를 지정해주어
리사이클러뷰 스크롤 시 상단 바가 접히게됩니다.
또한 enterAlways 로 리사이클러뷰 스크롤이 어느 부분에 있더라도 항상 동작합니다.
https://github.com/woowacourse-teams/2023-festa-go/assets/108349655/f753c47c-6127-40b1-b76d-d15aa431b0fa
https://github.com/woowacourse-teams/2023-festa-go/assets/108349655/6654874f-d479-434e-ab98-ac2d3aec2eef

[AN/USER] feat: 축제 목록 화면 UX 개선(#614)

---

.github/workflows/ci-back.yml

- closed: #633
`Cache Gradle packages` job을 통해 캐싱을 수행하여 실행 시간을 단축시켰습니다.
`gradlew build` 대신 `gradlew test`를 사용하여, 오버헤드를 줄였습니다.
자세한 변경 이력은 커밋 참조하시면 될 것 같습니다.

[BE] feat: CI workflow에 캐싱 및 버전 업데이트 적용 (#633)

---

backend/src/main/java/com/festago/stage/repository/StageRepository.java
backend/src/main/java/com/festago/stage/repository/StageRepositoryCustom.java
backend/src/main/java/com/festago/stage/repository/StageRepositoryCustomImpl.java
backend/src/main/java/com/festago/student/repository/StudentRepository.java
backend/src/main/java/com/festago/student/repository/StudentRepositoryCustom.java
backend/src/main/java/com/festago/student/repository/StudentRepositoryCustomImpl.java
backend/src/main/java/com/festago/ticket/repository/TicketAmountRepository.java
backend/src/main/java/com/festago/ticket/repository/TicketAmountRepositoryCustom.java
backend/src/main/java/com/festago/ticket/repository/TicketAmountRepositoryCustomImpl.java
backend/src/main/java/com/festago/ticket/repository/TicketRepository.java
backend/src/main/java/com/festago/ticket/repository/TicketRepositoryCustom.java
backend/src/main/java/com/festago/ticket/repository/TicketRepositoryCustomImpl.java

- closed: #627 
일단 모든 JPQL을 옮겼는데 사실 클래스가 2개가 늘어나니 이게 맞나? 싶기도 하고 미리 처내는게 좋겠다는 생각도 들더라고요.
컨벤션 같은 부분도 자의적인 부분이 있으니 여러분이 보시기에 합리적이지 않다 싶은 부분, 생각해보면 좋겠다 싶은 부분은 편하게 의견 남겨주세요.
코드단에도 코멘트를 남기겠습니다.

[BE] refactor: JPQL을 사용하는 Repository 메소드를 QueryDsl로 변경 (#627)

---

backend/build.gradle
backend/src/main/java/com/festago/admin/repository/AdminRepository.java
backend/src/main/java/com/festago/auth/application/AdminAuthService.java
backend/src/main/java/com/festago/auth/config/AuthConfig.java
backend/src/test/java/com/festago/admin/repository/MemoryAdminRepository.java
backend/src/test/java/com/festago/auth/application/AdminAuthServiceTest.java

- closed: #631
슬랙에서 얘기했던 [Spring Security Crypto](https://mvnrepository.com/artifact/org.springframework.security/spring-security-crypto) 라이브러리를 적용하였습니다.
`AuthService`가 가지는 암호화에 대한 의존성은 `PasswordEncoder` 인터페이스를 사용하였습니다.
따라서 테스트, 암호화 알고리즘의 변경에 대해서 유연하게 대응할 수 있도록 하였습니다.
`AuthConfig`에서 `PasswordEncoder` 구현체를 빈으로 등록하는데, 여기서 사용한 구현체는 `DelegatingPasswordEncoder` 클래스 입니다.
해당 구현체를 사용하여 비밀번호를 암호화하면 `{bcrypt}$2a$10$dXJ3...`과 같이 "{알고리즘}" 접두사가 붙습니다.
따라서 새로운 암호화 알고리즘을 적용했을 때, 기존 DB에 저장된 비밀번호를 호환시킬 때 문제가 발생될 여지를 없앨 수 있습니다.
자세한 내용은 [링크](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/password/DelegatingPasswordEncoder.html) 참조하시면 될 것 같습니다.
테스트 코드에서 구체적인 암호화 알고리즘은 필요하지 않으므로, 평문으로 저장되게 하는 "{noop}"를 사용하였습니다.
추가적으로 `PasswordEncoder`를 빈으로 등록할 때 …

[BE] feat: 어드민 비밀번호 암호화하여 저장 (#631)

---

backend/src/main/java/com/festago/student/domain/VerificationCode.java
backend/src/test/java/com/festago/student/domain/VerificationCodeTest.java

- closed: #447 
#482 에서 처리해야 했을 기능입니다.

[BE] fix: 학생 인증 코드가 유효하지 않을 시 500이 아닌 400 에러를 반환 (#447)

---

.github/workflows/cd-back-dev.yml

- closed: #641 
이슈 내용 그대로 입니다.
동시에 PR을 머지하는 상황에서 CD 작업이 여러 번 실행되지 않게 `concurrency` 설정을 추가했습니다.

[BE] feat: CD 작업 수행 시, 기존 CD 작업의 실행을 취소하여 동시에 CD가 되는 것을 방지 (#641)

---

backend/src/main/java/com/festago/auth/presentation/AdminAuthController.java
backend/src/test/java/com/festago/auth/presentation/AdminAuthControllerTest.java

- closed: #652
이슈 내용 그대로 잘못된 API의 경로를 수정했습니다.
이번 테스트에서 `@Nested`를 사용했는데, 가독성이 좋다면 다른 테스트도 다음과 같은 방법으로 작성해보는 것은 어떠신가요?
또한 `var` 타입을 테스트에서 사용하는 것 또한 좋아 보입니다.
(기존에 `AdminAuthController`가 없어서 소 잃고 외양간 고친 느낌이네요. 😂)

fix: AdminAuthController API 경로 수정 (#652)

---

backend/src/main/java/com/festago/auth/config/LoginConfig.java
backend/src/main/java/com/festago/common/interceptor/HttpMethodDelegateInterceptor.java
backend/src/main/java/com/festago/config/WebConfig.java
backend/src/main/resources/application-local.yml
backend/src/test/resources/application-test.yml

- closed: #654
CORS 설정을 추가했습니다.
CORS 설정을 `LoginConfig`에 두기는 애매해서, 새롭게 `WebConfig` 클래스를 만들었습니다.
URL 설정은 `application.yml`의 `festago.cors-allow-urls` 필드에 추가하면 됩니다.
`,`로 구분되니 새로운 도메인이 생기면 `http://foo.com,http://bar.com`과 같이 등록하면 됩니다.
---
preflight 요청에서 CORS 문제가 발생하여 `HttpMethodDelegateInterceptor`를 추가하고 적용했습니다.
prefilght 요청에는 쿠키와 헤더가 포함되지 않으므로 CORS 설정을 올바르게 하여도, 인증과 관련된 path로 요청이 오게 되면 CORS 문제가 발생합니다.
따라서 인증과 관련된 인터셉터에서는 `OPTIONS` HTTP 메서드를 제외한 요청만 검사해야 합니다.
`CorsUtils.isPreFlightRequest()` 메서드를 사용하는 방법도 있지만, 같은 path라도, HTTP 메서드 별로 인증 권한을 다르게 해야 할 일이 생길 것 같아 `HttpMethodDelegateInterceptor`를 적용했습니다.

feat: CORS 설정을 추가한다. (#654)

---

backend/src/main/java/com/festago/config/WebConfig.java
backend/src/main/resources/application-local.yml
backend/src/test/resources/application-test.yml

- closed: #659
이슈 내용과 같이 잘못된 CORS 설정을 수정했습니다.
`allowedOriginPatterns`의 인자로 들어가는 문자열은 `,`로 구분할 수 있기에 굳이 다시 배열로 만들어 넣어주는 작업은 하지 않았습니다.

fix: 잘못된 CORS 설정 수정 (#659)

---

backend/src/main/java/com/festago/festival/domain/FestivalQueryInfo.java
backend/src/main/resources/db/migration/V11__modify_school_and_festival_query_info.sql
backend/src/main/resources/db/migration/V12__add_festival_startdate_desc_index.sql

- closed: #685 
이슈 내용 그대로 `FesitvalQueryInfo`에 BaseTimeEntity 상속, `festival_id`에 대해 유니크 인덱스를 추가했습니다.
또한 `festival` 테이블에 대해 `start_date` 내림차순 인덱스를 추가했습니다.
이유는 다음과 같습니다.
```sql
explain
select f1_0.id,
f1_0.name,
f1_0.start_date,
f1_0.end_date,
f1_0.thumbnail,
s1_0.id,
s1_0.name,
s1_0.region,
f2_0.artist_info
from festival f1_0
join school s1_0
on f1_0.school_id = s1_0.id
join festival_query_info f2_0
on f2_0.festival_id = f1_0.id
where f1_0.start_date <= '2024-02-07'
and f1_0.end_date >= '2024-02-07'
order by f1_0.start_date desc,
f1_0.id
limit 6;
```
`start_date`는 이미 인덱스로 적용되어 있기 때문에 다음과 같이 `Backward index scan`이 적용될 것으로 예상할 수 있습니다.
하지만 `order by`에서 festival.id로 추가 정렬 조건 때문에 `using filesort`가 적용됩니다.
`festival` 테이블은 추가와 수정이 빈번하지 않은 테이블이기 때문에 인덱스 추가에 대한 부담이 적습니다. 
따라서 `start_date` 내림차순 인덱스를 …

[BE] feat: FesitvalQueryInfo에 BaseTimeEntity 상속, 유니크 인덱스 추가 (#685)

---

backend/src/main/java/com/festago/auth/presentation/AdminAuthController.java
backend/src/test/java/com/festago/auth/presentation/AdminAuthControllerTest.java

- closed: #696
이슈 내용과 같이 로그인 토큰 쿠키에 `sameSite=None` 속성을 추가했습니다.
추가로 관련 Controller 테스트 코드를 이전에 얘기했던 Controller 테스트 코드 컨벤션에 맞게 수정했습니다.
그리고 인증 관련 URI가 다음과 같이 되어있습니다.
`/admin/api/login`, `/admin/api/signup`, `/admin/api/initialize`
혼란을 방지하기 위해 다음과 같이 중간에 `/auth`를 추가해야 할 것 같습니다.
`/admin/api/auth/login`
지금 변경하게 되면 기존 어드민 사이트가 동작하지 않게 되므로 추후 새로운 백오피스 페이지가 기존 백오피스 페이지를 대체할 기능이 완성되면 변경하면 좋을 것 같습니다.

[BE] feat: Admin 로그인 쿠키에 sameSite=None 추가 (#696)

---

backend/src/main/java/com/festago/school/application/SchoolCommandService.java
backend/src/main/java/com/festago/school/domain/School.java
backend/src/main/java/com/festago/school/presentation/v1/SchoolV1Controller.java
backend/src/test/java/com/festago/school/application/integration/SchoolCommandServiceIntegrationTest.java

- closed: #689
이슈 내용 그대로 region 검증, 수정 기능, 주석 처리된 기능에 대해 활성화를 하였습니다.
추가로 `SchoolV1Controller`의 `findAllSchools` 메서드의 경우 `@ValidPageable`의 최대 사이즈를 50으로 변경하였습니다.
`Pageable`을 사용하는 일부 핸들러 메서드에도 해당 어노테이션을 붙여 검증을 단순화하는게 좋을 것 같습니다.

[BE] feat: School 도메인 region 검증, 수정 메서드 추가 및 주석 처리된 기능 활성화  (#689)

---

backend/src/main/java/com/festago/admin/presentation/v1/AdminSchoolV1Controller.java
backend/src/test/java/com/festago/admin/presentation/v1/AdminArtistV1ControllerTest.java
backend/src/test/java/com/festago/admin/presentation/v1/AdminSchoolV1ControllerTest.java

- closed: #693
이슈 내용 그대로 `@Valid` 어노테이션을 추가했고, Admin Controller 테스트에 권한 검증 테스트를 추가했습니다.

[BE] feat: Controller에 누락된 @Valid 어노테이션 추가, Admin Controller 테스트에 권한 검증 테스트 추가 (#693)

---

backend/src/main/java/com/festago/common/presentation/PingController.java
backend/src/test/java/com/festago/common/presentation/PingControllerTest.java

- closed: #703
이슈 내용과 같이 헬스 체크용 API를 추가했습니다.
경로는 다음과 같이 매핑됩니다.
`/ping`
응답은 200 상태 코드와 Body에 `pong`이 반환됩니다.

[BE] feat: 헬스 체크용 PingController 추가 (#703)

---

backend/src/main/resources/db/migration/V13__add_socialmedia.sql
backend/src/main/resources/db/migration/V14__add_imageurl_school_artist.sql

- closed: #707
`V14__add_imageurl_school_artist`에서 다음과 같이 잘못된 컬럼명을 추가하고 있습니다.
```sql
alter table school
add column logoUrl varchar(255);
alter table school
add column backgroundUrl varchar(255);
alter table artist
add column backgroundUrl varchar(255);
```
해당 컬럼명은 카멜 케이스가 아닌, 스네이크 케이스 형식이 되어야 합니다.
또한 `artist` 테이블의 `backgroundUrl` 컬럼은 `backgound_url`이 아닌 `background_image_url`이 되어야 합니다.
`school`은 `background_url` 이지만, `artist`가 `background_image_url`인 것이 좋아 보이진 않네요.
나중에 하나의 형식으로 통일해야 할 것 같습니다. (`@Embeddable`을 사용한 값타입도 좋아보이네요)
또한 머지가 되기 전 최종으로 V14와 V15의 내용을 합쳐도 좋을 것 같습니다.

[BE] 잘못된 flyway 스크립트 수정  (#707-hotfix1)

---

backend/src/main/java/com/festago/common/exception/ErrorCode.java
backend/src/main/java/com/festago/festival/presentation/v1/FestivalV1Controller.java
backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
backend/src/main/java/com/festago/school/domain/SchoolRegion.java
backend/src/test/java/com/festago/festival/presentation/v1/FestivalV1ControllerTest.java

- closed: #705
이슈 내용과 같이 `filter` 쿼리 파라미터 기본 값을 설정했습니다.
기본 값을 설정하는 방법은 회의에서 결정한 2번 방법을 사용해서 명시적으로 쿼리 파라미터를 표시했습니다.
최대 페이징 사이즈 검증 또한 `@ValidPageable` 어노테이션을 활용한 검증을 사용하도록 변경했습니다.
추가로 API 스펙에서는 지역이 `location`이 아닌, `region` 이므로 파라미터의 변수명 또한 변경했고, nullable 하지 않도록 default 값을 추가했습니다.
다만 추가로 문제가 발생할 우려가 있는 것이 기본 값을 지정하는 경우, Controller 단위 테스트로 완벽한 검증이 불가능합니다.
지금처럼 쿼리가 `location`에서 다른 값으로 변경되는 경우 실제 응답 값을 받아야 검증이 가능합니다.
예) 기존 쿼리가 location인데, region으로 바뀐 상황에서 특정 지역의 학교의 축제만 반환되길 기대하지만 모든 축제가 반환
따라서 Controller 단위 테스트만으로 검증을 할 수 없습니다.
하지만 이러한 변경은 현재 서비스가 실제 운영중이 아니므로 문제가 없지만, 운영중인 상황에서는 큰 문제가 될 수 있습니다.
따라서 쿼리 파라미터의 이름이 변경되는 경우에는 수정하지 않고, 새로운 버전의 컨트롤러를 만들어야 합니다.
그렇기 때문에 변경이 불가능한 상황에서 쿼리 파라미터의 유무를 테스트하는 것이 의문이 들기도 하네요.
물론 오타가 발생하여 `region`을 `regoin`으로 적을 수 있으나.. IDE의 오타 하이라이팅, 코드 리뷰로 해결할 수 있을 것 같기도 하여 …

[BE] fix: "/api/v1/festivals"의 "filter" 쿼리 파리미터 기본 값 지정 및 핸들러 메서드의 형식 변경 (#705)

---

backend/src/main/java/com/festago/admin/domain/Admin.java
backend/src/main/java/com/festago/auth/application/AdminAuthService.java

- closed: #612
`AdminAuthService`에 있던 `ROOT_ADMIN` 상수를 더 관련있는 `Admin` 도메인 클래스로 이동시켰습니다.

[BE] refactor: AdminAuthService 도메인 상수 도메인으로 이동 (#612)

---

backend/src/main/java/com/festago/auth/presentation/AdminAuthController.java
backend/src/test/java/com/festago/auth/presentation/AdminAuthControllerTest.java

- closed: #740
관리자 로그아웃 API를 추가했습니다.
로그아웃 API를 추가한 이유는 이슈에 남겨뒀으니 참고해주세요!
로그아웃 기능에는 변경이 없기에 모두가 접근할 수 있게 권한을 풀어도 되지만, 로그아웃을 하는 요청은 이미 권한을 얻은 뒤 요청을 하는 것이라 판단하여 따로 excludePathPatterns에 등록하지는 않았습니다. 
---
로그아웃 쿠키의 maxAge를 0으로 설정했는데, 지금 보니 로그인 쿠키에는 maxAge 설정이 되지 않아 세션으로 유지되네요!
이러면 보안에는 좋겠지만, 매번 브라우저를 재시작하면 로그인을 다시 해야할 것 같은데.. 관리자 기능인 만큼 보안이 중요하니 이대로 놔둬도 괜찮을 것 같은데 의견 있으시면 의견 남겨주세요!

[BE] feat: 관리자 로그아웃 API 추가 (#740)

---

backend/src/main/java/com/festago/admin/presentation/v1/dto/SchoolV1CreateRequest.java
backend/src/main/java/com/festago/admin/presentation/v1/dto/SchoolV1UpdateRequest.java
backend/src/main/java/com/festago/school/application/SchoolCommandService.java
backend/src/main/java/com/festago/school/domain/School.java
backend/src/main/java/com/festago/school/dto/SchoolCreateCommand.java
backend/src/main/java/com/festago/school/dto/SchoolUpdateCommand.java
backend/src/test/java/com/festago/acceptance/steps/AdminSchoolStepDefinitions.java
backend/src/test/java/com/festago/admin/presentation/v1/AdminSchoolV1ControllerTest.java
backend/src/test/java/com/festago/school/application/integration/SchoolCommandServiceIntegrationTest.java
backend/src/test/java/com/festago/school/domain/SchoolTest.java
backend/src/test/java/com/festago/support/SchoolFixture.java

- closed: #731
School 생성, 수정 시 누락된 `logoUrl`, `backgroundImageUrl`에 대한 필드를 추가했습니다.
적용 사항은 Request와 Command에 빌더 패턴을 적용했습니다.
이유는 School 생성 시 생성자의 인자에 String이 연속되기 때문에 실수로 인한 버그가 발생할 수 있기 때문입니다.
게다가 Request와 Command는 record이기 때문에 필드의 순서에 따라 생성자의 인자가 변합니다. (Request는 상관 없지만 테스트의 편의성과 가독성을 위해 적용했습니다.) 
TODO에도 남겨놨듯이 도메인에는 적용하지 않았지만, 도메인에도 적용하면 어떨까 하네요.
그리고 도메인이 가지고 있는 `logoUrl`, `backgroundImageUrl` 필드는 값 타입을 사용해도 좋을 것 같습니다.
이유는 해당 필드들이 공통점이 많기 때문이고, `Festival`, `Artist`에도 해당 개념이 사용되고 있습니다.
또한 기본 이미지 URL로 사용되는 경우에도 정적 변수로 할당하여 사용할 수 있을 것 같습니다. (ex: DEFAULT_POSTER_IMAGE_URL)
--- 
추가로 private 변수들만 `backgroundImageUrl`으로 변수명을 사용했습니다!

[BE] School 생성, 수정에 누락된 필드 추가 (#731)

---

backend/src/main/java/com/festago/artist/presentation/v1/ArtistDetailV1Controller.java
backend/src/main/java/com/festago/common/dto/SliceResponse.java
backend/src/main/java/com/festago/school/presentation/v1/SchoolV1Controller.java
backend/src/test/java/com/festago/artist/presentation/v1/ArtistDetailV1ControllerTest.java
backend/src/test/java/com/festago/school/presentation/v1/SchoolV1ControllerTest.java

- closed: #743 
```
{
"last":false,
"content":[
{
"id":1,
"name":"경북대학교",
"startDate":"2024-02-23",
"endDate":"2024-02-24",
"imageUrl":"www.image.com/image.png",
//원래 artists가 json 배열인데 테스트코드에선 String 넣어서 이래요
"artists":아티스트
}
]
}
```
우선 API 명세서와 같게, 또 필요한 값만 던져줬습니다. 
다만 구현에 있어 여러분들의 의견이 필요합니다.
저는 Repository와 Service에서 그대로 Slice를 넘겨주고 Controller에서 이를 last 여부만 가지는 SliceResponse 클래스로 변환해서 return 했습니다.
이렇게 한 이유는, 컨트롤러단에서만 하는게 코드 변경이 제일 적기 때문입니다. 
여러분들의 생각을 적어주세요.
1. ㅇㅇ 굿
2. 내 생각엔 Service에서 last만 가지게 변환해서 Controller에서 넘겨주는게 맞음.
3. 난 더 깊게 Repository에서 last만 가지는 값 뱉어주는게 맞다고 생각함.
일단 최대한 변경이 적은 방향으로 구현을 했고, 의견을 듣고 추가 push를 할려고 합니다.
변경이 더 많아지더라도, 어차피 코드가 많진 않아서 시간은 별로 안듭니다.

[BE] 아티스트 별 축제 조회, 학교 별 축제 조회시 API 명세서와 같은 Response를 전달 (#743)

---

backend/src/main/java/com/festago/admin/dto/ArtistCreateRequest.java
backend/src/main/java/com/festago/admin/dto/ArtistUpdateRequest.java
backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
backend/src/main/java/com/festago/artist/domain/Artist.java
backend/src/test/java/com/festago/admin/presentation/v1/AdminArtistV1ControllerTest.java
backend/src/test/java/com/festago/artist/application/integration/ArtistCommandServiceIntegrationTest.java

- closed: #732
Artist 생성, 수정에서 backgroundImgageUrl 을 함께 보내도록 수정 했습니다.
추가로 Artist 에서 사용하지 않는 생성자를 삭제했습니다.
글렌이 작업하신 예외 메시지 포맷을 따르기 위해서 @NotBlank의 메시지를 제거했습니다.

[BE] feat: Artist 생성, 수정에 누락된 필드를 추가한다.(#732)

---

android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListPopularViewHolder.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/popularfestival/PopularFestivalViewPagerAdapter.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/popularfestival/foreground/PopularFestivalForegroundAdapter.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalListUiState.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/PopularFestivalUiState.kt

- closed: #735 
1. PopularFestivalForegroundAdapter 를 리스트 어댑터에서 리사이클러뷰 어댑터로 변경합니다.
2. 아이템 개수를 Int.MaxValue 로 변경합니다.
3. 축제 목록에서 아이템 찾는 방법은 다음과 같습니다.
```kotlin
// 포지션을 총 아이템 개수로 나눈 나머지
val item = _festivals[position % _festivals.size]
```
4. 첫 시작을 전체 position 중간에서 시작합니다.
```kotlin
val initialPosition = Int.MAX_VALUE / 2 - (Int.MAX_VALUE / 2 % popularFestivals.size)
foregroundViewPager.setCurrentItem(initialPosition, false)
```
- (절반 - (절반을 아이템 개수로 나눈 나머지))
ex: 2147483647 / 2 는 1073741823
1073741823 을 5(아이템 개수)로 나눈 나머지 는 3
initialPosition 은 1073741823 - 3 인 1073741820 가 됩니다.
그럼 5로 나누어 떨어지므로 아이템은 0번째 index 부터 시작합니다.
- 여기서 2는 따로 상수화하지 않았습니다. 
5. DotIndicator 의 개수가 무한 개가 되어서 이를 BackgroundViewPager 와 연결시켰습니다.
- background 혼자 움직이면 안되니깐 터치 이벤트를 막았습니다. …

[AN/USER] feat: 축제 목록 화면 인기 축제 목록에 무한 스크롤을 적용한다(#735)

---

backend/src/main/java/com/festago/admin/application/AdminFestivalV1QueryService.java
backend/src/main/java/com/festago/admin/dto/AdminFestivalV1Response.java
backend/src/main/java/com/festago/admin/presentation/v1/AdminFestivalV1Controller.java
backend/src/main/java/com/festago/admin/repository/AdminFestivalV1QueryDslRepository.java
backend/src/main/java/com/festago/common/querydsl/OrderSpecifierUtils.java
backend/src/main/java/com/festago/common/querydsl/QueryDslHelper.java
backend/src/test/java/com/festago/admin/application/integration/AdminFestivalV1QueryServiceIntegrationTest.java
backend/src/test/java/com/festago/admin/presentation/v1/AdminFestivalV1ControllerTest.java

- closed: #745
관리자 페이지에서 축제 조회를 위한 기능을 추가했습니다.
~~#695 PR에서 `AdminFestivalV1Controller` API를 먼저 구현하고 있기 때문에 해당 PR이 머지되면 API를 추가해야 할 것 같습니다.~~
해당 작업 완료 했습니다.
중요하게 봐야할 사항은 `AdminFestivalV1QueryDslRepository`가 의존하고 있는 `QueryDslHelper` 클래스인데, 해당 클래스는 기존 상속으로 사용하던 `QueryDslRepositorySupport` 추상 클래스의 Bean 버전입니다.
왜 기존에 잘 만들어둔 `QueryDslRepositorySupport`을 상속하지 않고 `QueryDslHelper`를 의존해서 사용했냐면, 여러 이유가 있는데 그 중 가장 큰 이유는 정렬을 할 때 발생하는 문제 때문입니다.
`applyPagination` 메서드를 사용하면 `orderBy`를 해주지 않아도 정렬이 되는데 이유는 `querydsl.applyPagination()` 메서드를 호출할 때 Pageable 객체만 넘기면 정렬이 자동으로 되기 때문입니다.
자동으로 정렬이 되게 하는 마법같은 일은 `QueryDslRepositorySupport`의 생성자로 받는 도메인 클래스를 분석해서 해당 도메인 클래스가 가진 필드를 기준으로 프로퍼티를 설정함으로 이뤄집니다.
```java
protected QueryDslRepositorySupport(Class<?> domainClass) {
this.domainClass = domainClass;
}
@Autowired …
```

[BE] feat: 관리자 축제 조회 기능 추가 (#745)

---

android/festago/presentation/src/main/res/layout/item_artist_detail_artist.xml
android/festago/presentation/src/main/res/layout/item_festival_detail_stage.xml
android/festago/presentation/src/main/res/layout/item_festival_list_artist.xml
android/festago/presentation/src/main/res/layout/item_school_detail_artist.xml

- closed: #777 
https://github.com/woowacourse-teams/2023-festa-go/assets/108349655/9927df7e-0dd7-47b9-b3af-d040c9db5e15
아티스트 아이템 뒤에 배경색이 있어서 테두리와 겹쳐지는 문제가 있습니다.
아티스트 아이템 뒤에 배경색을 없앴습니다.
축제 상세 아이템 배경테두리있는 drawable 로 바꿔주었습니다.
10분

[AN/USER] 축제 목록, 공연 목록의 디자인을 수정한다.(#777)

---

android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/bindingadapter/Image.kt

- closed: #775 
Glide 에 placeholder, fallback, error 이미지를 background_gray_03 color 로 변경했습니다.
placeholder : 이미지 불러오기 전까지 보여준다.
fallback : 이미지가 널이면 보여준다
error : 이미지 불러오기에 실패하면 보여준다. 
https://github.com/woowacourse-teams/2023-festa-go/assets/108349655/e3860774-56a8-4d71-b033-0c958b38dff7
10분

[AN/USER] feat: 이미지 로딩 전까지 기본 이미지를 보여준다.(#775)

---

android/festago/data/src/main/java/com/festago/festago/data/dto/artist/ArtistResponse.kt
android/festago/data/src/main/java/com/festago/festago/data/dto/festival/FestivalResponse.kt

- closed: #792 
FestivalResponse, ArtistResponse 수정해서 서버 응답 정상적으로 받을 수 있도록 했습니다.

[AN/USER] API 변경 사항 반영 (#792)

---

backend/src/main/java/com/festago/auth/annotation/MemberAuth.java
backend/src/main/java/com/festago/auth/config/LoginConfig.java
backend/src/main/java/com/festago/common/interceptor/AnnotationDelegateInterceptor.java
backend/src/test/java/com/festago/auth/config/LoginConfigTest.java

- closed: #789 
이슈 내용 그대로 컨트롤러의 핸들러 메서드에 어노테이션을 붙여 인증을 수행하는 기능을 추가했습니다.
구현은 위임 패턴을 사용한 `AnnotationDelegateInterceptor`에 핸들러 메서드에 붙일 어노테이션 클래스와 동작하게 할 인터셉터를 추가하면 되도록 했습니다.
위임 패턴을 사용한 이유는 추후 `Member` 외 `Manager` 또는 `Staff` 권한에 대한 인증이 필요할 수 있기 때문입니다.
따라서 다른 권한에 대한 인증 인터셉터 클래스를 만들지 않고 기능을 추가할 수 있도록 했습니다.
굳이 인증이 아니라도 로깅, 횟수 제한 등 여러 용도로 사용이 가능할 것 같네요.
어드민 패키지에 사용되는 컨트롤러에는 모두 인증이 필요하므로 기존 `HttpMethodDelegateInterceptor`를 그대로 사용하면 될 것 같네요.
(그게 아니라면 모든 핸들러 메서드마다 `@AdminAuth`를 붙여야 하니..)

[BE] feat: 컨트롤러의 핸들러 메서드에 어노테이션을 붙여 인증을 수행하는 기능 추가 (#789)

---

backend/src/main/java/com/festago/auth/config/LoginConfig.java
backend/src/test/java/com/festago/auth/config/LoginConfigTest.java

- closed: #804 
이슈 내용과 같이 정적 파일 접근 시 `ResourceHttpRequestHandler` 타입의 클래스를 `HandlerMethod`로 형변환 하는 도중 발생하던 `ClassCastException` 문제를 수정했습니다.
`AnnotationDelegateInterceptor`에 `/api/**` 경로를 지정하여, 정적 파일 접근 시 해당 인터셉터 사용을 제외하였습니다.
큰 수정이 없고, 놔둔다면 에러가 계속 발생하므로 바로 머지 처리하겠습니다.

[BE] fix: AnnotationDelegateInterceptor에 경로 추가하여 ClassCastException 방지 (#804)

---

.github/workflows/cd-back-dev.yml
.gitmodules
backend/Dockerfile
backend/src/main/resources/application.yml

- closed: #826
이슈 내용과 같이 새로운 환경에서 서버를 실행하기 위해 서브 모듈을 업데이트 했습니다.
또한 기존 프로퍼티를 관리하던 폴더를 `festago-config/backend` 이름으로 사용하며 직접 config 파일을 `application.yml`에 명시하였지만, 이름을 변경하며 명시할 필요가 없도록 하였습니다.
(실제 작동하는 것을 보려면 dev, prod 말고 infra를 사용해주세요. 슬랙에 알람와요 😂)
---
추가로 기존 인프라의 Nginx를 도커로 구동하면서 스프링 서버도 도커로 구성하게 되었는데, 변경에 맞춰 CD Github Action도 변경했습니다!

[BE] refactor: 서브모듈 위치 변경 및 경로 변경 (#826)

---

backend/src/main/java/com/festago/artist/infrastructure/JsonArtistsSerializer.java

- closed: #831
이슈 내용 그대로 Artist를 직렬화할 때 엔티티 그대로 직렬화 하는 것을 `ArtistQueryModel`을 정의하여 직렬화 하도록 했습니다.
해당 이슈 빠르게 처리되지 않으면 클라이언트에서 처리가 불가능하므로 우선 바로 머지하겠습니다.
추가 변경 또는 더 나은 개선 방향이 있다면 새롭게 이슈로 파서 처리하면 될 것 같습니다!

fix: Artist 직렬화 ArtistQueryModel로 변환 후 직렬화 하도록 변경 (#831)

---

backend/src/main/java/com/festago/admin/domain/Admin.java
backend/src/main/java/com/festago/auth/application/AdminAuthService.java
backend/src/main/java/com/festago/auth/application/command/AdminAuthCommandService.java
backend/src/main/java/com/festago/auth/config/LoginConfig.java
backend/src/main/java/com/festago/auth/domain/AuthType.java
backend/src/main/java/com/festago/auth/dto/AdminLoginRequest.java
backend/src/main/java/com/festago/auth/dto/AdminLoginV1Request.java
backend/src/main/java/com/festago/auth/dto/AdminLoginV1Response.java
backend/src/main/java/com/festago/auth/dto/AdminSignupRequest.java
backend/src/main/java/com/festago/auth/dto/AdminSignupResponse.java
backend/src/main/java/com/festago/auth/dto/AdminSignupV1Request.java
backend/src/main/java/com/festago/auth/dto/command/AdminLoginCommand.java
backend/src/main/java/com/festago/auth/dto/command/AdminLoginResult.java
backend/src/main/java/com/festago/auth/dto/command/AdminSignupCommand.java
backend/src/main/java/com/festago/auth/presentation/AdminAuthController.java
backend/src/main/java/com/festago/auth/presentation/v1/AdminAuthV1Controller.java
backend/src/test/java/com/festago/auth/application/AdminAuthServiceTest.java
backend/src/test/java/com/festago/auth/application/command/AdminAuthCommandServiceTest.java
backend/src/test/java/com/festago/auth/presentation/AdminAuthControllerTest.java
backend/src/test/java/com/festago/auth/presentation/v1/AdminAuthV1ControllerTest.java

- closed: #797
이슈 내용과 같이 관리자 페이지에서 사용해야 할 기능을 위해 로그인 시 새로운 응답을 추가했습니다.
(해당 PR이 머지되면 관리자 페이지에서 로그인이 불가능해지므로, 기존 기능들은 Deprecated 처리 했습니다!)
구현하며 논의하고 싶은 내용이 있는데, `AdminLoginResult` 클래스의 TODO 주석으로 길게 남겼지만,  Command Service에서 반환하는 객체의 이름을 무엇으로 해야할지 모르겠네요. 😂
지금은 버저닝이 적용되었다 하더라도, V2와 같은 새로운 버전이 필요하지 않기 때문에 Service에서 View에 필요한 Response를 그대로 반환해도 되지만, 어드민 로그인 응답의 토큰 값은 응답의 JSON 필드가 아닌, 쿠키로 전송되어야 합니다.
또한 클라이언트에서 불필요한 JSON 필드는 무시하기 때문에 Service에서 반환한 필드를 그대로 반환해도 상관 없으나, 토큰과 같이 보안에 직접적으로 관련된 값은 클라이언트에서 굳이 필요하지 않다면 보내지 않는 것이 올바른 것 같습니다.
따라서 Controller에서 Service에서 반환한 값을 그대로 반환하기엔 무리가 있습니다.
(레이어드 아키텍쳐 관점에서 어긋나기도 하구요 😂)
따라서 `AdminLoginResult`와 같이 View에 의존적이지 않은 응답 객체를 보내어 Controller에서 가공하여 사용하도록 했습니다.
(Response라고 이름을 지으려니, Controller에서 그대로 반환해도 될 객체 같아 Result로 했습니다)
다른 의견이 있으시면 남겨주세요!!

[BE] feat: 관리자 로그인 응답 변경 및 AdminController 버저닝 적용 (#797)

---

backend/src/main/java/com/festago/artist/domain/ArtistsSerializer.java
backend/src/test/java/com/festago/stage/application/command/StageCommandServiceIntegrationTest.java
backend/src/test/java/com/festago/stage/application/command/StageCreateServiceTest.java
backend/src/test/java/com/festago/stage/application/command/StageDeleteServiceTest.java
backend/src/test/java/com/festago/stage/application/command/StageUpdateServiceTest.java
backend/src/test/java/com/festago/stage/domain/validator/festival/OutOfDateStageFestivalUpdateValidatorTest.java
backend/src/test/java/com/festago/support/fixture/FestivalQueryInfoFixture.java

- closed: #813 
변경한 것 
1. PR 제목 그대로 fixture를 사용하도록 변경
2. 테스트에서 Repository 타입을 fake 구현체가 아닌 interface를 가지도록 변경, ```@BeforeEach```에서 clear 호출 안하고 객체 새로 만들어주는 방식으로 데이터 리셋
3. CommandService로 생성하던 것을 Repository로 생성하도록 변경
4. 지금은 FestivalQueyInfoFixture로 테이블에 저장하는 것이 불가능합니다. 아래와 같이 구현된 상태인데 info 필드가 not null이라서 제약 조건 에러가 발생해요. 그래서 임시적으로 다음과 같이 변경했어요
Before
```
public FestivalQueryInfo build() {
FestivalQueryInfo festivalQueryInfo = FestivalQueryInfo.create(festivalId);
festivalQueryInfo.updateArtistInfo(null, ignore -> artistInfo);
return festivalQueryInfo;
}
```
After
```
//TODO FestivalQueryInfo에 ArtistInfo를 String으로 넣어줄 수가 없음..
public FestivalQueryInfo build() {
return FestivalQueryInfo.create(festivalId);
}
```
FestivalQueryInfo에 생성자를 public으로 하던지.. ArtistInfo 필드를 빌더에서 빼던지 등 수정해야 할 것 같네요.

 [BE] refactor: stage 테스트 패키지에서 엔티티 생성을 픽스쳐를 사용하여 생성하도록 변경 (#813)

---

backend/src/test/java/com/festago/festival/application/integration/command/FestivalCreateServiceTest.java
backend/src/test/java/com/festago/festival/application/integration/command/FestivalDeleteServiceTest.java
backend/src/test/java/com/festago/festival/application/integration/command/FestivalUpdateServiceTest.java
backend/src/test/java/com/festago/festival/application/integration/query/FestivalDetailV1QueryServiceIntegrationTest.java
backend/src/test/java/com/festago/festival/application/integration/query/FestivalSearchV1QueryServiceTest.java
backend/src/test/java/com/festago/festival/application/integration/query/FestivalV1QueryServiceIntegrationTest.java
backend/src/test/java/com/festago/festival/application/integration/query/PopularFestivalV1QueryServiceIntegrationTest.java

- closed #814 
festival 패키지 내에 Fixture를 사용하도록 변경했습니다.
또한 기존 패키지를 변경했는데 기존 내역은 다음과 같습니다.
```
├── FestivalQueryInfoArtistRenewServiceTest.java
├── QueryDslSchoolSearchRecentFestivalV1QueryServiceIntegrationTest.java
├── command
│   ├── FestivalCreateServiceTest.java
│   ├── FestivalDeleteServiceTest.java
│   └── FestivalUpdateServiceTest.java
└── integration
├── FestivalDetailV1QueryServiceIntegrationTest.java
├── FestivalSearchV1QueryServiceTest.java
├── FestivalV1QueryServiceIntegrationTest.java
└── PopularFestivalV1QueryServiceIntegrationTest.java
```
command 패키지 내부에도 다 integration 테스트여서 다음과 같이 변경했습니다.
```bash
├── FestivalQueryInfoArtistRenewServiceTest.java
├── QueryDslSchoolSearchRecentFestivalV1QueryServiceIntegrationTest.java
└── integration
├── command
│   ├── …
```

[BE] refactor: festival 테스트 패키지에서 엔티티 생성을 픽스쳐를 사용하여 생성하도록 변경 (#814)

---

backend/build.gradle.kts

- closed: #843
이슈 내용과 같이 `commons-logging.jar` 관련 로그와 잠재적인 충돌 문제를 해결했습니다.

fix: commons-logging.jar 로그 제거 및 빌드 시 제외 (#843)

---

backend/src/main/java/com/festago/admin/application/AdminSocialMediaV1QueryService.java
backend/src/main/java/com/festago/admin/dto/socialmedia/AdminSocialMediaV1Response.java
backend/src/main/java/com/festago/admin/dto/socialmedia/SocialMediaCreateV1Request.java
backend/src/main/java/com/festago/admin/dto/socialmedia/SocialMediaUpdateV1Request.java
backend/src/main/java/com/festago/admin/presentation/v1/AdminSocialMediaV1Controller.java
backend/src/main/java/com/festago/admin/repository/AdminSocialMediaV1QueryDslRepository.java
backend/src/main/java/com/festago/common/exception/ErrorCode.java
backend/src/main/java/com/festago/socialmedia/application/SocialMediaCommandService.java
backend/src/main/java/com/festago/socialmedia/domain/OwnerType.java
backend/src/main/java/com/festago/socialmedia/domain/SocialMedia.java
backend/src/main/java/com/festago/socialmedia/dto/command/SocialMediaCreateCommand.java
backend/src/main/java/com/festago/socialmedia/dto/command/SocialMediaUpdateCommand.java
backend/src/main/java/com/festago/socialmedia/repository/SocialMediaRepository.java
backend/src/test/java/com/festago/admin/application/integration/AdminSocialMediaV1QueryServiceIntegrationTest.java
backend/src/test/java/com/festago/admin/presentation/v1/AdminSocialMediaV1ControllerTest.java
backend/src/test/java/com/festago/socialmedia/application/SocialMediaCommandServiceTest.java
backend/src/test/java/com/festago/socialmedia/repository/MemorySocialMediaRepository.java

- closed: #802
관련 이슈처럼 소셜미디어 CRUD 기능을 추가했습니다.
이슈에서는 CUD 기능만 추가하기로 되어 있지만, 관리자 페이지에 빠르게 기능 구현이 필요하고, 구현의 어려움이 없으므로 해당 PR에서 작업하였습니다.
소셜미디어의 추가와 수정에 문자열의 길이에 대한 검증 로직이 없는데, 관리자 기능이라 추가하지는 않았습니다.
(추후 500 에러가 발생하는 것을 보고 추가하면 될 것 같네요)
소셜미디어 조회 API는 2개인데, 그중 식별자를 통한 단건 조회 기능은 수정 기능에서 사용할 목적으로 만들었습니다. (상세 조회)
목록 조회는 `ownerId`, `ownerType`에 해당하는 소셜미디어를 모두 조회해 오는데, 따로 limit을 두지는 않았습니다.
이유는 `ownerId`와 `ownerType`의 조합에서 생성할 수 있는 소셜미디어의 최대 개수는 `socialMediaType` 개수와 동일하기에, 너무 많은 row로 인해 발생하는 성능 이슈가 없습니다. 
`SocialMediaType.values().length`를 limit 절에 사용한다면 나름 성능 최적화가 가능할 것 같네요. 다만 모든 socialMediaType을 만드는 경우가 없을 것 같아 현실성은 떨어져 보입니다. 😂
또한 `SocialMediaCommandService`의 TODO 주석에서 남겨두었지만, 추상화된 예외가 필요할지 얘기하고 싶습니다.
더 객체 지향적인 방법으로 풀어나간다면 SocialMediaCreateValidator 인터페이스를 만들어서 어떻게 할 것 같은데...
현재 소셜미디어의 owner는 …

[BE] feat: 소셜미디어 CRUD 기능 추가 (#802)

---

backend/src/main/java/com/festago/admin/application/AdminStageV1QueryService.java
backend/src/main/java/com/festago/admin/presentation/v1/AdminStageV1Controller.java
backend/src/main/java/com/festago/admin/repository/AdminStageV1QueryDslRepository.java
backend/src/test/java/com/festago/admin/application/integration/AdminStageV1QueryServiceIntegrationTest.java
backend/src/test/java/com/festago/admin/presentation/v1/AdminStageV1ControllerTest.java

- closed: #855
이슈 내용 그대로 `AdminStageV1Controller`에 공연의 식별자로 공연을 조회하는 기능을 추가했습니다.
`AdminStageV1QueryServiceIntegrationTest`에서 각 메서드 별 `@Nested`로 묶은 것 빼고는 크게 볼게 없을거라 생각되네요.
그 외 메서드 명을 어떻게 통일해야 하나 거슬리긴 하는데... 사소한 부분이니 나중에 운영 단계에서 리팩터링하면 좋을 것 같습니다.

[BE] feat: AdminStageV1Controller에 공연 단건 조회 기능 추가 (#855)

---

backend/src/main/java/com/festago/stage/application/command/StageDeleteService.java

- closed: #857 
이슈 내용과 같이 공연을 삭제할 때 발생하는 외래키 제약 조건으로 발생하는 에러를 수정했습니다.
큰 변경은 없으나, 외래키 제약으로 인한 문제가 계속 발생하면 외래키 제약을 없애는 것도 좋을 것 같네요.

[BE] fix: 공연 삭제 메서드 순서 변경하여 외래키 제약 에러 수정 (#857)

---

backend/src/main/java/com/festago/bookmark/application/ArtistBookmarkV1QueryService.java
backend/src/main/java/com/festago/bookmark/dto/v1/ArtistBookmarkInfoV1Response.java
backend/src/main/java/com/festago/bookmark/repository/v1/ArtistBookmarkV1QueryDslRepository.java

- closed: #869
`ArtistBookmarkInfoV1Response`에 누락된 아티스트 식별자를 추가했습니다.
수정되어야 클라이언트에서 북마크 기능을 구현 가능하기 때문에 바로 머지하도록 하겠습니다!

[BE] fix: ArtistBookmarkInfoV1Response에 아티스트 식별자 추가 (#869)

---

backend/build.gradle.kts

- closed: #873
Spring Actuator, Prometheus 의존성을 추가했습니다.
세부 설정은 `application.yml`에 정의해야 하므로, 의존성 추가 외에 작업은 없습니다.
Actuator로 열린 엔드포인트는 서브모듈 참고하시면 될 것 같습니다!

[BE] Spring Actuator, Prometheus 의존성 추가 (#873)

---

backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
backend/src/test/java/com/festago/school/application/integration/SchoolV1QueryServiceIntegrationTest.java

- closed: #883
학교의 축제 목록을 조회할 때, `last` 여부가 반대로 발생하는 버그를 수정했습니다.
원인은 `SchoolV1QueryDslRepository`에서 `createResponse()` 메서드의 `hasNext` 변수를 세팅하는 로직이 반대로 되어 있더군요. 😂
테스트 코드에서 또한 잘못된 assertion으로 인해 검증할 수 없었습니다.
이러한 버그가 발생한 근본적 원인은 `last` 여부를 설정하는 로직이 중복되어 있기 때문이라고 생각합니다.
지금은 단순히 버그를 수정했지만, 근본적인 문제를 수정하려면 last 여부를 판단하는 로직을 공통으로 사용하도록 해야할 것 같네요.
클라이언트에 영향이 가는 문제이기 때문에 바로 머지하겠습니다!

[BE] fix: 학교의 축제 목록을 조회할 때 last 여부가 반대로 반환되는 버그를 수정 (#883)

---

android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListMoreItemViewHolder.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalMoreItemUiState.kt
android/festago/presentation/src/main/res/anim/fade_in.xml
android/festago/presentation/src/main/res/anim/fade_out.xml
android/festago/presentation/src/main/res/anim/no_anim.xml
android/festago/presentation/src/main/res/anim/slide_in.xml
android/festago/presentation/src/main/res/anim/slide_out.xml
android/festago/presentation/src/main/res/layout/fragment_search.xml
android/festago/presentation/src/main/res/layout/item_artist_detail_festival.xml
android/festago/presentation/src/main/res/layout/item_festival_list_popular.xml
android/festago/presentation/src/main/res/layout/item_festival_list_tab.xml
android/festago/presentation/src/main/res/navigation/festival_list.xml

- closed: #876 
- slide_in : 오른쪽에서 왼쪽으로 슬라이드로 등장하면서 서서히 나타난다
- slide_out : 왼쪽에서 오른쪽으로 슬라이드 되면서 서서히 사라진다.
- no_anim : 그대로 유지한다. (설정을 안해주니깐 빈 화면이 되어버려서 추가했습니다.)
- fade_in : 서서히 나타난다.
- fade_out: 서서히 사라진다.
상세화면으로 들어가는 것들은 모두 slide 를 사용했습니다.
검색 화면은 fade 로 들어갑니다.
1. 기존 방식
스크롤 이벤트가 발생했을 때 리사이클러뷰 바닥에 도달하면 요청
바닥에 도달해야지만 재요청하기 때문에 문제 발생
2. FestivalMoreItemUiState (Progress Bar View) 의 바인드 이용
바인드되는 시점에 람다 함수를 실행. 바인드는 실제로 보이기 이전에 발생하기 때문에 보다 자연스러운 스크롤이 가능.
물론 겁나 빨리 스크롤하면 끊김.

[AN/USER] feat: 애니메이션 수정 축제 로딩 개선(#876)

---

android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailFragment.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailViewModel.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/uistate/ArtistDetailUiState.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailFragment.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailViewModel.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/uiState/FestivalDetailUiState.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalListUiState.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFragment.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailViewModel.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/uistate/SchoolDetailUiState.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/SearchFragment.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/SearchViewModel.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/uistate/SearchUiState.kt
android/festago/presentation/src/main/res/layout/fragment_artist_detail.xml
android/festago/presentation/src/main/res/layout/fragment_festival_detail.xml
android/festago/presentation/src/main/res/layout/fragment_festival_list.xml
android/festago/presentation/src/main/res/layout/fragment_school_detail.xml
android/festago/presentation/src/main/res/layout/fragment_search.xml

- closed: #898 
FestivalList / FestivalDetail / SchoolDetail / Search 화면에 에러 화면과 새로 고침 기능을 추가했습니다.

[AN/USER] feat: 에러 화면, 새로고침 적용 (#898)

---

backend/src/main/java/com/festago/auth/application/command/MemberAuthFacadeService.java
backend/src/main/java/com/festago/auth/config/AuthConfig.java
backend/src/main/java/com/festago/auth/domain/OpenIdClient.java
backend/src/main/java/com/festago/auth/domain/OpenIdClients.java
backend/src/main/java/com/festago/auth/domain/OpenIdNonceValidator.java
backend/src/main/java/com/festago/auth/domain/OpenIdUserInfoProvider.java
backend/src/main/java/com/festago/auth/domain/UserInfo.java
backend/src/main/java/com/festago/auth/dto/KakaoUserInfo.java
backend/src/main/java/com/festago/auth/dto/v1/OpenIdLoginV1Request.java
backend/src/main/java/com/festago/auth/infrastructure/CachedOpenIdKeyProvider.java
backend/src/main/java/com/festago/auth/infrastructure/FestagoOpenIdClient.java
backend/src/main/java/com/festago/auth/infrastructure/KakaoOpenIdClient.java
backend/src/main/java/com/festago/auth/infrastructure/KakaoOpenIdJwksClient.java
backend/src/main/java/com/festago/auth/infrastructure/KakaoOpenIdJwksErrorHandler.java
backend/src/main/java/com/festago/auth/infrastructure/KakaoOpenIdPublicKeyLocator.java
backend/src/main/java/com/festago/auth/infrastructure/KakaoOpenIdUserInfoProvider.java
backend/src/main/java/com/festago/auth/infrastructure/NoopOpenIdNonceValidator.java
backend/src/main/java/com/festago/auth/presentation/v1/MemberAuthV1Controller.java
backend/src/main/java/com/festago/common/exception/ErrorCode.java
backend/src/test/java/com/festago/auth/infrastructure/CachedOpenIdKeyProviderTest.java
backend/src/test/java/com/festago/auth/infrastructure/KakaoOpenIdJwksClientTest.java
backend/src/test/java/com/festago/auth/infrastructure/KakaoOpenIdUserInfoProviderTest.java
backend/src/test/java/com/festago/auth/presentation/v1/MemberAuthV1ControllerTest.java

- closed: #909 
OpenID Connect 방식의 인증 기능을 추가했습니다.
사용자는 OAuth2로 인증을 수행하고, `accessToken`을 서버로 보내지 않고 `idToken`을 서버로 보냅니다.
`idToken`은 JWT 토큰 형식으로, 모든 정보가 노출되어 있는데, 이걸로 어떻게 신원을 검사하냐면, OAuth2 서버에서 비밀키로 서명된 JWT 토큰을  OAuth2 서버에 공개키를 요청하여, 서버에서 해당 공개키로 IdToken이 수정되지 않은 토큰임을 검사합니다.
따라서 악의적으로 토큰을 수정해서 보내더라도, 서버에서 해당 토큰이 수정되었는지 판단할 수 있으므로 보안에 문제가 없습니다!
카카오에서 제공하는 OpenID 유효성 검증 절차는 다음과 같습니다.
---
1. ID 토큰의 영역 구분자인 온점(.)을 기준으로 헤더, 페이로드, 서명을 분리
2. 페이로드를 Base64 방식으로 디코딩
3. 페이로드의 iss 값이 https://kauth.kakao.com와 일치하는지 확인
4. 페이로드의 aud 값이 서비스 앱 키와 일치하는지 확인
5. 페이로드의 exp 값이 현재 UNIX 타임스탬프(Timestamp)보다 큰 값인지 확인(ID 토큰이 만료되지 않았는지 확인)
6. 페이로드의 nonce 값이 카카오 로그인 요청 시 전달한 값과 일치하는지 확인
7. 서명 검증
서명 검증은 다음 순서로 진행합니다.
1. 헤더를 Base64 방식으로 디코딩
2. [OIDC: 공개키 목록 조회하기](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-a …

[BE] feat: OpenID Connect 방식의 인증 기능 추가 (#909)

---

backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2AccessTokenClient.java
backend/src/main/java/com/festago/auth/infrastructure/KakaoOpenIdUserInfoProvider.java
backend/src/main/java/com/festago/auth/infrastructure/OpenIdIdTokenParser.java
backend/src/test/java/com/festago/auth/infrastructure/KakaoOpenIdUserInfoProviderTest.java
backend/src/test/resources/application-test.yml

- closed: #916
이슈에서 얘기한 것 처럼, 앱 환경에서 id 토큰의 `aud` 값이 REST API 키와 달라 검증이 되지 않는 문제를 수정했습니다.
다른 환경의 토큰 `aud` 값이 native app, REST API 키 둘 중 하나라도 일치하면 유효성 검사를 통과한 것이라 판단하였습니다.
그 외 JWT 토큰을 파싱할 때 로직이 다른 서비스 구현체(Apple)가 생기면 중복이 발생할 것 같아, 미리 분리해두었습니다.
클라이언트에서 빠르게 반영해야 하므로 우선 바로 머지 처리 하도록 하겠습니다!

[BE] OAuth2 설정에 native app key 설정 추가 및 id 토큰 유효성 검사 수정 (#916)

---

backend/src/main/java/com/festago/artist/dto/ArtistFestivalDetailV1Response.java
backend/src/main/java/com/festago/artist/infrastructure/JsonArtistsSerializer.java
backend/src/main/java/com/festago/festival/dto/FestivalSearchV1Response.java
backend/src/main/java/com/festago/festival/dto/FestivalV1Response.java
backend/src/main/java/com/festago/festival/dto/StageV1Response.java
backend/src/main/java/com/festago/school/dto/v1/SchoolFestivalV1Response.java

- closed: #920
이슈에서 말한 것 처럼 스웨거 문서에 `@JsonRawValue` 어노테이션이 붙은 필드가 정상적으로 JSON 포맷이 보이도록 수정했습니다.

[BE] fix: 아티스트 목록 스웨거 문서에서 정확하게 표시되도록 변경 (#920)

---

backend/src/main/java/com/festago/artist/repository/ArtistDetailV1QueryDslRepository.java
backend/src/main/java/com/festago/common/querydsl/QueryDslHelper.java
backend/src/main/java/com/festago/common/querydsl/QueryDslRepositorySupport.java
backend/src/main/java/com/festago/festival/repository/FestivalSearchCondition.java
backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java

- closed: #885
기존 중복으로 처리되던 커서 기반 페이징 로직을 공통으로 처리하도록 했습니다.
문제는 QueryDSL을 편하게 사용하기 위해 만든 Support 클래스가 2개 있다는 점인데, 둘 중 하나를 선택해야 할 것 같습니다.
`QueryDslRepositorySupport`는 상속을 해야 사용 가능하며, 부모 생성자를 호출하고 `Class<T>` 타입의 변수를 넣어줘야 합니다.
`QueryDslHelper`는 빈으로 주입 받으며, 딱히 뭘 하지 않아도 됩니다.
이것만 보면, 상속보다 조합을 사용하고, 굳이 번거로운 일을 하지 않아도 되는 `QueryDslHelper`를 사용하는게 좋아 보이지만, `QueryDslRepositorySupport`은 나름대로 장점이 있습니다.
바로 `QueryDslRepositorySupport`의 `applyPagination` 메서드는 `Pageable`의 `Sort` 객체에 따라 자동으로 정렬이 가능하도록 해줍니다.
(해당 내용은 #749 PR 참조하시면 될 것 같습니다.)
우선 비교를 위해 각 클래스를 사용한 버전을 만들어 뒀습니다.
보시고 어떤게 좋아보이는지 리뷰 남겨주시면 해당 클래스를 사용한 버전으로 리팩터링 하면 될 것 같네요!

[BE] feat: 커서 기반 페이징 처리 시 last 여부를 설정하는 로직을 공통으로 처리 (#885)

---

backend/src/main/java/com/festago/admin/dto/socialmedia/SocialMediaCreateV1Request.java
backend/src/main/java/com/festago/admin/dto/socialmedia/SocialMediaUpdateV1Request.java
backend/src/main/java/com/festago/socialmedia/dto/command/SocialMediaCreateCommand.java
backend/src/main/java/com/festago/socialmedia/dto/command/SocialMediaUpdateCommand.java

- closed: #938
이슈에 적은 내용처럼 SocialMediaUpdateCommand, SocialMediaCreateCommand에 빌더 패턴을 적용하여, logoUrl과 url이 반대로 적용되는 문제를 수정했습니다.
추후 이러한 문제가 발생하지 않도록 Command 전부에 빌더 패턴을 적용하여 사용하는 것이 좋을 것 같네요.
운영 환경에서 발생하고 있는 문제이므로 바로 머지 하도록 하겠습니다!

fix: SocialMediaUpdateCommand, SocialMediaCreateCommand 빌더 패턴 사용 (#938)

---

backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
backend/src/test/java/com/festago/artist/application/ArtistCommandServiceTest.java

- closed: #948
이슈 내용대로 아티스트 생성, 수정, 삭제시 이벤트 발행 로직을 추가했습니다.
해당 사항 지속되면 추후 이미지 삭제 로직 구현 시 기존 이미지가 모두 사라질 수 있기에 최대한 빠르게 처리해야 합니다.
따라서 리뷰 없이 바로 머지하도록 하겠습니다!

[BE] fix: 아티스트 생성, 수정, 삭제 이벤트 발행 추가 (#948)

---

android/festago/app/build.gradle.kts
android/festago/data/src/main/java/com/festago/festago/data/repository/DefaultUserRepository.kt
android/festago/data/src/main/java/com/festago/festago/data/repository/FakeUserRepository.kt
android/festago/data/src/main/java/com/festago/festago/data/retrofit/AuthInterceptor.kt
android/festago/domain/src/main/java/com/festago/festago/domain/repository/UserRepository.kt

- closed: #941 
1. refresh 요청 전에 토큰을 파기한다. (요청은 보내고 응답 받지 않은 채로 종료할 수 있기 때문)
2. refresh 성공 시 새로 갈아끼운다.

[AN/USER] fix: refresh 토큰 인증 오류 수정(#941)

---

backend/src/main/java/com/festago/artist/application/ArtistDetailV1QueryService.java
backend/src/main/java/com/festago/artist/dto/ArtistFestivalV1Response.java
backend/src/main/java/com/festago/artist/dto/ArtistMediaV1Response.java
backend/src/main/java/com/festago/artist/presentation/v1/ArtistDetailV1Controller.java
backend/src/main/java/com/festago/artist/presentation/v1/ArtistSearchV1Controller.java
backend/src/main/java/com/festago/artist/presentation/v1/ArtistV1Controller.java
backend/src/main/java/com/festago/artist/repository/ArtistDetailV1QueryDslRepository.java
backend/src/main/java/com/festago/auth/presentation/v1/MemberAuthV1Controller.java
backend/src/main/java/com/festago/bookmark/presentation/v1/ArtistBookmarkV1Controller.java
backend/src/main/java/com/festago/bookmark/presentation/v1/BookmarkManagementV1Controller.java
backend/src/main/java/com/festago/bookmark/presentation/v1/FestivalBookmarkV1Controller.java
backend/src/main/java/com/festago/bookmark/presentation/v1/SchoolBookmarkV1Controller.java
backend/src/main/java/com/festago/common/presentation/PingController.java
backend/src/main/java/com/festago/entry/presentation/MemberEntranceController.java
backend/src/main/java/com/festago/entry/presentation/StaffMemberTicketController.java
backend/src/main/java/com/festago/fcm/presentation/MemberFCMController.java
backend/src/main/java/com/festago/festival/presentation/v1/FestivalSearchV1Controller.java
backend/src/main/java/com/festago/festival/presentation/v1/FestivalV1Controller.java
backend/src/main/java/com/festago/festival/presentation/v1/PopularFestivalV1Controller.java
backend/src/main/java/com/festago/member/presentation/MemberController.java
backend/src/main/java/com/festago/school/presentation/v1/SchoolSearchV1Controller.java
backend/src/main/java/com/festago/school/presentation/v1/SchoolV1Controller.java
backend/src/main/java/com/festago/student/presentation/StudentController.java
backend/src/main/java/com/festago/ticketing/presentation/MemberTicketController.java
backend/src/test/java/com/festago/artist/application/integration/ArtistDetailV1QueryServiceIntegrationTest.java
backend/src/test/java/com/festago/artist/presentation/v1/ArtistDetailV1ControllerTest.java
backend/src/test/java/com/festago/artist/presentation/v1/ArtistV1ControllerTest.java

- closed: #959
이슈에 적은 내용대로 사용되지 않는 `Pageable` 파라미터가 표시되는 문제를 해결했습니다.
또한 각자 Controller를 작업하다 보니, Swagger 문서의 내용이 통일되지 않아 혼란이 있는 관계로 형식을 모두 통일 시켰습니다.
Swagger가 자동화를 해주는 것은 참 좋긴 한데.. 오히려 불편하기도 하네요. 😂
그렇다고 REST Docs를 사용하기에는 공수가 너무 많이 필요하기도 하고...
아무튼 그렇습니다. 😂

[BE] fix: Swagger 문서에 잘못된 Parameter 수정 및 형식 통일 (#959)

---

backend/src/main/java/com/festago/admin/dto/artist/ArtistV1CreateRequest.java
backend/src/main/java/com/festago/admin/dto/artist/ArtistV1UpdateRequest.java
backend/src/main/java/com/festago/admin/dto/socialmedia/SocialMediaCreateV1Request.java
backend/src/main/java/com/festago/admin/dto/socialmedia/SocialMediaUpdateV1Request.java
backend/src/main/java/com/festago/artist/domain/Artist.java
backend/src/main/java/com/festago/common/util/ImageUrlHelper.java
backend/src/main/java/com/festago/festival/domain/Festival.java
backend/src/main/java/com/festago/member/domain/Member.java
backend/src/main/java/com/festago/mock/domain/MockFestivalsGenerator.java
backend/src/main/java/com/festago/mock/domain/MockSchoolsGenerator.java
backend/src/main/java/com/festago/school/domain/School.java
backend/src/main/java/com/festago/socialmedia/domain/SocialMedia.java
backend/src/test/java/com/festago/member/domain/MemberTest.java
backend/src/test/java/com/festago/school/domain/SchoolTest.java

- closed: #952
도메인에 대해 기본 이미지에 대한 정책을 빈 문자열("")으로 설정했습니다.
따라서 모든 엔티티 생성, 수정 요청 시 이미지 필드는 nullable 하도록 변경하였습니다.

[BE] 기본 이미지 URL 정책 빈 문자열로 변경 (#952)

---

backend/src/main/resources/db/migration/V5__modify_member_social_id.sql

- closed: #965
이슈에 남긴 내용대로 member 테이블의 social_id 컬럼의 길이를 45글자로 늘렸습니다.
단순 DB 컬럼 길이 반영이므로 리뷰 없이 머지하도록 하겠습니다!

fix: member 테이블 social_id 컬럼 길이 45글자 수정 (#965)

---

backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
backend/src/main/java/com/festago/festival/repository/ArtistFestivalSearchV1QueryDslRepository.java
backend/src/test/java/com/festago/festival/application/integration/query/FestivalSearchV1QueryServiceTest.java

- closed: #926 
검색 로직은 기존에
~ 대학교 혹은 ~대로 끝난다면 축제 이름에 해당 대학교 이름이 적힌 축제를 반환하고 나머지 경우에 아티스트 이름을 기반으로 검색하였습니다.
변경된 로직은
해당 이름에 해당하는 아티스트가 있는지 확인하고 없으면 축제 이름에 해당 키워드가 포함되어 있다면 반환하도록 변경하였습니다.
이로 인해 부경만 쳤을 경우 부경이란 키워드가 포함된 모든 축제를 받을 수 있습니다.
축제 이름에 해당 키워드가 포함되었는지 확인하는 것이기 때문에 만약 "축제"로 검색을 한다면 "축제"가 이름에 포함된 모든 축제가 반환됩니다.
이 부분에 대한 방어 로직을 짜려했으나 앱 초기에는 데이터도 얼마 없을 뿐더러 후에 페이징 적용시에 고려해도 좋을 것이라 판단하여 최대한 검색이 자유롭게 되도록 그대로 두었습니다.

[BE] feat: 축제 대학교 검색 기능 보완 및 정렬(#926)

---

backend/src/main/java/com/festago/admin/application/AdminQueryInfoRenewalService.java
backend/src/main/java/com/festago/admin/dto/queryinfo/QueryInfoRenewalFestivalPeriodV1Request.java
backend/src/main/java/com/festago/admin/presentation/v1/AdminQueryInfoRenewalV1Controller.java
backend/src/main/java/com/festago/admin/repository/AdminFestivalIdResolverQueryDslRepository.java
backend/src/main/java/com/festago/admin/repository/AdminStageIdResolverQueryDslRepository.java
backend/src/main/java/com/festago/stage/application/StageQueryInfoEventListener.java
backend/src/main/java/com/festago/stage/application/StageQueryInfoService.java
backend/src/test/java/com/festago/admin/presentation/v1/AdminQueryInfoRenewalV1ControllerTest.java
backend/src/test/java/com/festago/admin/repository/AdminFestivalIdResolverQueryDslRepositoryTest.java
backend/src/test/java/com/festago/admin/repository/AdminStageIdResolverQueryDslRepositoryTest.java
backend/src/test/java/com/festago/artist/infrastructure/DelimiterArtistsSerializer.java
backend/src/test/java/com/festago/stage/application/StageQueryInfoServiceTest.java
backend/src/test/java/com/festago/stage/repository/MemoryStageQueryInfoRepository.java
backend/src/test/java/com/festago/support/fixture/FestivalFixture.java

- closed: #933
이슈에 적은 내용대로, 관리자 페이지에 사용할 QueryInfo를 초기화하는 API를 추가했습니다.
구현한 재갱신 방법은 두 가지가 있습니다.
1. 축제의 식별자와 같은 경우
2. 두 날짜를 받아, 축제의 시작일이 포함되는 축제인 경우
1번은 단순히 축제의 식별자를 받아, 해당 축제+공연 QueryInfo를 재갱신 합니다.
2번은 두 날짜를 받고, 축제의 시작일이 해당 두 날짜 범위에 포함되는 축제+공연 QueryInfo를 재갱신 합니다.
주의사항으로 2번의 경우 날짜를 넉넉하게 잡아버리면, 모든 축제+공연에 대해 재갱신이 이뤄지므로 잠깐 부하가 크게 발생할 수 있습니다.
(운영 환경에서는 축제 개수가 작으므로 큰 문제는 없을 것 같네요)

[BE] feat: FestivalQueryInfo, StageQueryInfo를 재갱신하는 어드민 API 추가 (#933)

---

backend/src/main/java/com/festago/upload/application/ImageFileUploadService.java
backend/src/main/java/com/festago/upload/domain/FileExtension.java
backend/src/test/java/com/festago/upload/application/ImageFileUploadServiceTest.java

- closed: #946
ImageFileUploadService에서 `jpeg`, ~~`webp`~~ 확장자에 대한 지원을 추가했습니다.
~~참고로 `webp` 확장자가 좋은 점이, png에 비해 용량이 2~3배 정도 작습니다. (png 561kb, webp 204kb)~~
~~가능하다면 이미지 업로드는 `webp`로 변환한 뒤 올리는 게 좋을 것 같습니다.~~
`webp` 확장자 지원은 iOS 이슈로 인해 삭제하였습니다. 😂

[BE] feat: ImageFileUploadService jpeg 확장자 지원 추가 (#946)

---

backend/src/main/java/com/festago/admin/dto/upload/AdminDeleteAbandonedPeriodUploadFileV1Request.java
backend/src/main/java/com/festago/admin/presentation/v1/AdminUploadFileDeleteV1Controller.java
backend/src/main/java/com/festago/admin/presentation/v1/AdminUploadImageV1Controller.java
backend/src/main/java/com/festago/upload/application/UploadFileDeleteService.java
backend/src/main/java/com/festago/upload/domain/StorageClient.java
backend/src/main/java/com/festago/upload/infrastructure/R2StorageClient.java
backend/src/main/java/com/festago/upload/repository/UploadFileRepository.java
backend/src/test/java/com/festago/admin/presentation/v1/AdminUploadFileDeleteV1ControllerTest.java
backend/src/test/java/com/festago/admin/presentation/v1/AdminUploadImageV1ControllerTest.java
backend/src/test/java/com/festago/upload/application/UploadFileDeleteServiceTest.java
backend/src/test/java/com/festago/upload/infrastructure/FakeStorageClient.java
backend/src/test/java/com/festago/upload/repository/MemoryUploadFileRepository.java

- closed: #956
Uploaded 상태로 오래되거나 Abandoned 상태의 UploadFile을 삭제하는 기능을 추가했습니다.
파일을 삭제할 때 `S3Client.deleteObject()` 메서드를 사용하지 않고 `S3Client.deleteObjects()` 메서드를 사용했습니다.
이유는 파일을 삭제할 때, 요청을 한 번씩 여러 번 보내는 것 보다, 한 번의 요청으로 모든 파일을 삭제하는 것이 효율적이라고 판단했습니다.
그에 따라 실패한 요청이 있을 수 있으므로 에러가 있는지 확인하고, 에러가 있으면 로그를 남기는 식으로 구현했습니다.
(FCM과 비슷하네요. Javadoc에 `that if the object specified in the request is not found, Amazon S3 returns the result as deleted` 라는 내용이 있습니다. 따라서 권한 문제가 아니라면 에러가 날 일이 있을까 싶네요 😂)
파일을 삭제하면, DB 데이터도 당연히 삭제를 해야하는데, JPA의 `Query Creation` 기능을 사용하지 않고, `@Query` 어노테이션을 사용하여 JPQL로 작성했습니다.
이유는 Query Creation 기능을 사용하면 in절로 사용을 했다고 생각했지만, delete 쿼리가 별도로 날아갑니다..!
이에 대한 자세한 내용은 [동욱님 블로그](https://jojoldu.tistory.com/235) 참고하시면 될 것 같습니다.
덤으로 바로 `List<UploadFile>` 타입을 넘길 수 있어서도 있습니다. 😂
그 외 삭제할 대상을 찾기 위해 …

[BE] feat: Uploaded 상태로 오래되거나 Abandoned 상태의 UploadFile을 삭제하는 기능 추가 (#956)

---

backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
backend/src/main/java/com/festago/artist/repository/ArtistRepository.java
backend/src/main/java/com/festago/common/exception/ErrorCode.java
backend/src/test/java/com/festago/artist/application/ArtistCommandServiceTest.java
backend/src/test/java/com/festago/artist/repository/MemoryArtistRepository.java

- closed: #963
Artist 생성 시 이름으로 중복이 있는지 검사하는 기능을 추가했습니다.
큰 기능이 아니라, 크게 적을 내용이 없네요. 😂

[BE] feat: Artist 생성 시 중복 이름 검증 추가 (#963)

---

backend/src/main/java/com/festago/auth/application/command/MemberAuthCommandService.java
backend/src/main/java/com/festago/auth/domain/UserInfo.java
backend/src/main/java/com/festago/auth/domain/UserInfoMemberMapper.java
backend/src/main/java/com/festago/member/config/DefaultNicknamePolicyConfig.java
backend/src/main/java/com/festago/member/domain/DefaultNicknamePolicy.java
backend/src/main/java/com/festago/member/domain/Member.java
backend/src/main/java/com/festago/member/infrastructure/DefaultNicknamePolicyImpl.java
backend/src/test/java/com/festago/auth/application/command/MemberAuthCommandServiceTest.java
backend/src/test/java/com/festago/member/domain/MemberTest.java
backend/src/test/java/com/festago/member/infrastructure/DefaultNicknamePolicyImplTest.java

- closed: #972
이슈에 남긴 내용대로 사용자의 기본 닉네임 정책을 추가했습니다.
`Member` 엔티티에 static 메서드를 가진 클래스를 사용해서 기본 닉네임을 사용하려고 했으나..
테스트가 불가능한 문제도 있고, static 메서드를 사용하는 것이 불편해서, 객체지향적으로 구현했습니다. 😂
기본 닉네임을 정하는 것은 좋은데, 사용자가 기본 닉네임이 마음에 들지 않아 할 수 있어서, 닉네임 변경 기능이 필요하지 않을까 싶네요.

[BE] feat: 사용자 기본 닉네임 정책 추가 (#972)

---

android/festago/data/src/main/java/com/festago/festago/data/util/ResponseExt.kt
android/festago/domain/src/main/java/com/festago/festago/domain/exception/BookmarkLimitExeededException.kt
android/festago/domain/src/main/java/com/festago/festago/domain/exception/NetworkException.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailViewModel.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailViewModel.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailViewModel.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/artistsearch/ArtistSearchViewHolder.kt
android/festago/presentation/src/main/res/layout/fragment_bookmark_list.xml
android/festago/presentation/src/main/res/layout/item_search_artist.xml
android/festago/presentation/src/main/res/values/strings.xml

- closed: #978 
- 로그인이 필요합니다 → 로그인이 필요해요 로 변경
- 아티스트를 북마크 했습니다 → 북마크에 추가했어요 로 변경
- 북마크 탭 이동 (보라색 보임)
[Screen_recording_20240519_123412.webm](https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/586828e1-2e81-42d9-a8c9-992f4d922d56)

[AN/USER] 디자인 수정 및 Domain Exception 추가 (#978) 

---

android/festago/data/src/main/java/com/festago/festago/data/util/ResponseExt.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailViewModel.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/festival/ArtistDetailFestivalViewHolder.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/bookmarklist/festivalbookmark/adapater/FestivalBookmarkViewHolder.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListFestivalViewHolder.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFestivalViewHolder.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFragment.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailViewModel.kt
android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/festivalsearch/FestivalSearchViewHolder.kt
android/festago/presentation/src/main/res/layout/fragment_bookmark_list.xml
android/festago/presentation/src/main/res/layout/fragment_my_page.xml
android/festago/presentation/src/main/res/layout/item_artist_detail_festival.xml
android/festago/presentation/src/main/res/layout/item_festival_bookmark.xml
android/festago/presentation/src/main/res/layout/item_festival_list_festival.xml
android/festago/presentation/src/main/res/layout/item_school_bookmark.xml
android/festago/presentation/src/main/res/layout/item_school_detail_festival.xml
android/festago/presentation/src/main/res/layout/item_search_artist.xml
android/festago/presentation/src/main/res/layout/item_search_festival.xml
android/festago/presentation/src/main/res/layout/item_search_school.xml

- closed: #986
서버로 isPast == true 를 요청할 때
lastFestivalId, lastLocalDate 가 past 가 아니면 데이터가 제대로 반환되지 않습니다.
그래서 그 로직을 수정했습니다.
추가로 10 개 요청을 20개 요청으로 늘렸습니다. (서버는 페이징이 되고 있지 않기 때문에..)
**30개로 늘리면 400 에러가 발생합니다 참고해주세요!**

[AN/USER] fix: 상세 화면 축제 목록 요청 로직 변경 및 Throwable 예외 처리 제거(#986)

---

backend/build.gradle.kts
backend/src/main/java/com/festago/bookmark/domain/Bookmark.java
backend/src/main/java/com/festago/member/domain/Member.java
backend/src/main/java/com/festago/school/domain/School.java
backend/src/main/java/com/festago/socialmedia/domain/SocialMedia.java
backend/src/main/java/com/festago/stage/domain/Stage.java
backend/src/main/java/com/festago/ticket/domain/Ticket.java
backend/src/main/java/com/festago/ticketing/domain/MemberTicket.java
backend/src/main/java/com/festago/upload/domain/UploadFile.java

- closed: #989
제목 그대로 Hibernate의 버그를 수정하기 위해 Spring Boot 버전을 3.2.5로 올렸습니다.
그에따라 수정한 점이 있는데, 엔티티에 Enum을 필드로 사용하는 곳에서 명확하게 `columnDefinition`을 지정해주어야 합니다.
이유는 [Hibernate 6.2](https://docs.jboss.org/hibernate/orm/6.2/migration-guide/migration-guide.html#ddl-implicit-datatype-enum) 부터 변경사항이 생겼기 때문인데, MySQL을 사용한다면 기본으로 데이터타입을 `ENUM`으로 사용한다고 합니다.
하지만 DB 테이블에서 컬럼의 데이터 타입에 ENUM을 사용하는 것은 [안티 패턴](https://gompro.postype.com/post/8253823)이라고 하더군요.
(저 또한 마찬가지로, DB가 비즈니스 로직을 알게되므로 안티패턴이라고 생각합니다 😂)
그 외 테스트를 돌렸을 때 발생하는 문제는 없었습니다.
(기존 버전이 3.1.4를 사용했으니, 마이너 버전 업데이트이므로 크리티컬한 변경은 없어 보입니다)
해당 PR이 머지가 되면 RestTemplate을 사용하던 코드를 RestClient를 사용하도록 리팩터링해도 좋아보이네요.

[BE] chore: Spring Boot 3.2.5 버전 업그레이드 (#989)
