woowacourse-teams/2023-festa-go

- android/festago/app/src/main/res/values-night/themes.xml
- android/festago/app/src/main/res/values/colors.xml
- android/festago/app/src/main/res/values/dimens.xml
- android/festago/app/src/main/res/values/themes.xml
- closed: #24 
페스타고 유저 어플 Material 리소스 적용
colors / dimens / themes 설정
> [AN/USER] FEAT: 페스타고 유저 어플 Material 리소스 적용(#24)

- backend/build.gradle
- backend/intellij-java-festago-style.xml
- backend/src/main/java/com/festago/FestaGoApplication.java
- backend/src/test/java/com/festago/FestaGoApplicationTests.java
- closed: #34
Google Style Guide Format 적용
기존 파일 서식 정리
> [BE] style: Google Style Guide Format 적용 (#34)

- .github/PULL_REQUEST_TEMPLATE.md
- closed: #37 
- 변경 전: `[BE] FEAT: ~~(#issueNum)`
- 변경 후: `[BE] feat: ~~(#issueNum)`
> [ALL] docs: PR 제목의 타입을 소문자로 변경 (#37)

- backend/build.gradle
- backend/src/main/java/com/festago/application/EntryService.java
- backend/src/main/java/com/festago/config/EntryProviderConfig.java
- backend/src/main/java/com/festago/domain/EntryCode.java
- backend/src/main/java/com/festago/domain/EntryCodeProvider.java
- backend/src/main/java/com/festago/domain/EntryState.java
- backend/src/main/java/com/festago/domain/Member.java
- backend/src/main/java/com/festago/domain/MemberTicket.java
- backend/src/main/java/com/festago/domain/MemberTicketRepository.java
- backend/src/main/java/com/festago/domain/Ticket.java
- backend/src/main/java/com/festago/dto/EntryCodeResponse.java
- backend/src/main/java/com/festago/infrastructure/JwtEntryCodeProvider.java
- backend/src/main/java/com/festago/presentation/TicketController.java
- backend/src/main/resources/application-local.yml
- backend/src/test/java/com/festago/application/EntryServiceTest.java
- backend/src/test/java/com/festago/domain/MemberTicketTest.java
- backend/src/test/java/com/festago/domain/TicketTest.java
- backend/src/test/java/com/festago/infrastructure/JwtEntryCodeProviderTest.java
- backend/src/test/java/com/festago/presentation/TicketControllerTest.java
- closed: #26 
도메인 클래스 추가
JWT 의존성 추가
티켓 제시용 QR 생성 API 추가
> [BE] feat: 티켓 제시용 QR 생성 기능 구현 (#26)

- android/festago/app/build.gradle.kts
- android/festago/app/src/main/AndroidManifest.xml
- android/festago/app/src/main/java/com/festago/festago/data/MockWeb.kt
- android/festago/app/src/main/java/com/festago/festago/data/RetrofitClient.kt
- android/festago/app/src/main/java/com/festago/festago/data/dto/StageDto.kt
- android/festago/app/src/main/java/com/festago/festago/data/dto/TicketCodeDto.kt
- android/festago/app/src/main/java/com/festago/festago/data/dto/TicketDto.kt
- android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
- android/festago/app/src/main/java/com/festago/festago/data/service/TicketRetrofitService.kt
- android/festago/app/src/main/java/com/festago/festago/domain/model/Stage.kt
- android/festago/app/src/main/java/com/festago/festago/domain/model/Ticket.kt
- android/festago/app/src/main/java/com/festago/festago/domain/model/TicketState.kt
- android/festago/app/src/main/java/com/festago/festago/domain/model/timer/Timer.kt
- android/festago/app/src/main/java/com/festago/festago/domain/repository/TicketRepository.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
- closed: #42 
1. retrofit을 이용해서 서버에서 데이터를 받아오도록 수정
2. Mock서버 구축하여 임시 연결
3. 타이머가 바로 시작되지 않는 현상 수정
> [AN/USER] feat: 티켓 정보를 받아오는 API 연동 (#42)

- backend/src/main/java/com/festago/application/EntryService.java
- backend/src/main/java/com/festago/application/MemberTicketService.java
- backend/src/main/java/com/festago/domain/MemberRepository.java
- backend/src/main/java/com/festago/domain/MemberTicket.java
- backend/src/main/java/com/festago/domain/MemberTicketRepository.java
- backend/src/main/java/com/festago/domain/Stage.java
- backend/src/main/java/com/festago/domain/StageRepository.java
- backend/src/main/java/com/festago/domain/Ticket.java
- backend/src/main/java/com/festago/domain/TicketRepository.java
- backend/src/main/java/com/festago/dto/EntryCodeResponse.java
- backend/src/main/java/com/festago/dto/MemberTicketResponse.java
- backend/src/main/java/com/festago/dto/MemberTicketsResponse.java
- backend/src/main/java/com/festago/dto/StageResponse.java
- backend/src/main/java/com/festago/presentation/TicketController.java
- backend/src/main/resources/application-local.yml
- backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
- backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
- backend/src/test/java/com/festago/presentation/TicketControllerTest.java
> [BE] feat: 유저의 티켓 조회 기능 구현 (#25) 

- android/festago/app/src/test/java/com/festago/festago/presentation/ticketentry/TicketEntryViewModelTest.kt
- closed: #55 
- 티켓 받기 기능 테스트 작성
> [AN/USER] test: 티켓 제시 화면 티켓 받기 테스트 작성 (#55)

- backend/src/main/java/com/festago/application/EntryService.java
- backend/src/main/java/com/festago/config/EntryCodeConfig.java
- backend/src/main/java/com/festago/domain/EntryCode.java
- backend/src/main/java/com/festago/domain/EntryCodeExtractor.java
- backend/src/main/java/com/festago/domain/EntryCodePayload.java
- backend/src/main/java/com/festago/domain/EntryCodeProvider.java
- backend/src/main/java/com/festago/domain/EntryState.java
- backend/src/main/java/com/festago/domain/MemberTicket.java
- backend/src/main/java/com/festago/dto/TicketValidationRequest.java
- backend/src/main/java/com/festago/dto/TicketValidationResponse.java
- backend/src/main/java/com/festago/infrastructure/JwtEntryCodeExtractor.java
- backend/src/main/java/com/festago/infrastructure/JwtEntryCodeProvider.java
- backend/src/main/java/com/festago/presentation/StaffTicketController.java
- backend/src/test/java/com/festago/application/EntryServiceTest.java
- backend/src/test/java/com/festago/domain/EntryStateTest.java
- backend/src/test/java/com/festago/domain/MemberTicketTest.java
- backend/src/test/java/com/festago/infrastructure/JwtEntryCodeExtractorTest.java
- backend/src/test/java/com/festago/infrastructure/JwtEntryCodeProviderTest.java
- backend/src/test/java/com/festago/presentation/StaffTicketControllerTest.java
> [BE] feat: 스태프 티겟 검사 기능 구현 (#27)

- backend/src/main/java/com/festago/config/DemoDataInitConfig.java
- backend/src/main/java/com/festago/demo/DemoController.java
- backend/src/main/java/com/festago/domain/Ticket.java
- backend/src/main/resources/application-local.yml
> [BE] feat: 더미 데이터 생성 (#62)

- .github/workflows/ci-back.yml
- backend/src/main/java/com/festago/presentation/TicketController.java
> [BE] feat: dev 브랜치에 CI workflow 추가 (#67)

- android/festago-staff/app/build.gradle.kts
- android/festago-staff/app/src/main/java/com/festago/festagostaff/data/RetrofitClient.kt
- android/festago-staff/gradle.properties
- android/festago/app/build.gradle.kts
- android/festago/app/src/main/java/com/festago/festago/data/RetrofitClient.kt
- android/festago/gradle.properties
- closed: #69
- 유저 어플의 서버 URL을 비밀값으로 변경
- 스태프 어플의 서버 URL을 비밀값으로 변경
> [AN/USER/STAFF] feat: 유저와 스태프 어플 서버 비밀 값으로 변경 (#69)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainBinding.kt
- closed: #72 
- 빌드 해보지 않고 PR 머지시켜서 죄송합니다...
> [AN/USER] 리소스 변경사항 반영 (#72)

- android/festago-staff/app/src/main/AndroidManifest.xml
- android/festago-staff/app/src/main/java/com/festago/festagostaff/presentation/extension/ActivityExtension.kt
- android/festago-staff/app/src/main/java/com/festago/festagostaff/presentation/ui/ticketvalidation/TicketValidationActivity.kt
- android/festago-staff/app/src/main/res/values/strings.xml
> [AN/STAFF] fix: 카메라 권한 요청(#77)

- android/festago-staff/.gitignore
- android/festago-staff/app/build.gradle.kts
- android/festago-staff/build.gradle.kts
- closed: #82 
- 베타 테스트 배포를 위한 파이어베이스 연동
> [AN/STAFF] feat: 파이어 베이스 연동(#82)

- android/festago/app/.gitignore
- android/festago/app/build.gradle.kts
- android/festago/build.gradle.kts
- closed: #81 
- 베타 테스트 배포를 위한 파이어베이스 연동
> [AN/USER] feat: 파이어 베이스 연동(#81)

- .github/workflows/assign-reviewer.yml
> [ALL] feat: Assign Reviewer By Label에 사용되는 토큰을 GITHUB_TOKEN으로 변경 (#85)

- backend/src/main/java/com/festago/infrastructure/JwtEntryCodeExtractor.java
> [BE] refactor: JwtEntryCodeExtractor에서 사용하는 JwtParser를 로컬 변수에서 멤버 변수로 이동 (#97)

- .github/workflows/assign-reviewer.yml
> [ALL] feat: 라벨에 따라 리뷰어를 자동 할당하는 Action 변경 (#89)

- backend/src/main/java/com/festago/demo/DemoController.java
- backend/src/main/java/com/festago/domain/MemberTicket.java
- backend/src/main/java/com/festago/domain/Ticket.java
- backend/src/main/java/com/festago/infrastructure/JwtEntryCodeProvider.java
- backend/src/test/java/com/festago/application/EntryServiceTest.java
- backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
- backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
- backend/src/test/java/com/festago/domain/MemberTicketTest.java
- backend/src/test/java/com/festago/domain/TicketTest.java
- backend/src/test/java/com/festago/infrastructure/JwtEntryCodeExtractorTest.java
- backend/src/test/java/com/festago/infrastructure/JwtEntryCodeProviderTest.java
- backend/src/test/java/com/festago/support/MemberFixture.java
- backend/src/test/java/com/festago/support/MemberTicketFixture.java
- backend/src/test/java/com/festago/support/StageFixture.java
- backend/src/test/java/com/festago/support/TicketFixture.java
>  [BE] feat: 테스트 픽스쳐 제작 및 불필요한 도메인 생성자 제거 (#54) 

- backend/src/main/java/com/festago/application/EntryService.java
- backend/src/main/java/com/festago/application/MemberTicketService.java
- backend/src/main/java/com/festago/domain/EntryCode.java
- backend/src/main/java/com/festago/domain/EntryCodePayload.java
- backend/src/main/java/com/festago/domain/EntryState.java
- backend/src/main/java/com/festago/domain/MemberTicket.java
- backend/src/main/java/com/festago/dto/ErrorResponse.java
- backend/src/main/java/com/festago/dto/MemberTicketResponse.java
- backend/src/main/java/com/festago/dto/MemberTicketsResponse.java
- backend/src/main/java/com/festago/exception/BadRequestException.java
- backend/src/main/java/com/festago/exception/ErrorCode.java
- backend/src/main/java/com/festago/exception/FestaGoException.java
- backend/src/main/java/com/festago/exception/InternalServerException.java
- backend/src/main/java/com/festago/exception/NotFoundException.java
- backend/src/main/java/com/festago/infrastructure/JwtEntryCodeExtractor.java
- backend/src/main/java/com/festago/infrastructure/JwtEntryCodeProvider.java
- backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
- backend/src/main/java/com/festago/presentation/TicketController.java
- backend/src/test/java/com/festago/application/EntryServiceTest.java
- backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
- backend/src/test/java/com/festago/domain/EntryStateTest.java
- backend/src/test/java/com/festago/domain/MemberTicketTest.java
- backend/src/test/java/com/festago/infrastructure/JwtEntryCodeExtractorTest.java
- backend/src/test/java/com/festago/infrastructure/JwtEntryCodeProviderTest.java
> [BE] feat: 커스텀 예외 생성 및 예외 처리 도입 (#78)

- backend/src/main/java/com/festago/config/DemoDataInitConfig.java
- backend/src/main/java/com/festago/demo/DemoController.java
- backend/src/main/java/com/festago/domain/Festival.java
- backend/src/main/java/com/festago/domain/FestivalRepository.java
- backend/src/main/java/com/festago/domain/Member.java
- backend/src/main/java/com/festago/domain/MemberTicket.java
- backend/src/main/java/com/festago/domain/Stage.java
- backend/src/main/java/com/festago/domain/Ticket.java
- backend/src/main/java/com/festago/domain/TicketType.java
- backend/src/main/java/com/festago/dto/StageResponse.java
- backend/src/main/java/com/festago/exception/ErrorCode.java
- backend/src/test/java/com/festago/application/EntryServiceTest.java
- backend/src/test/java/com/festago/domain/FestivalTest.java
- backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
- backend/src/test/java/com/festago/domain/StageTest.java
- backend/src/test/java/com/festago/infrastructure/JwtEntryCodeProviderTest.java
- backend/src/test/java/com/festago/presentation/TicketControllerTest.java
- backend/src/test/java/com/festago/support/FestivalFixture.java
- backend/src/test/java/com/festago/support/MemberFixture.java
- backend/src/test/java/com/festago/support/MemberTicketFixture.java
- backend/src/test/java/com/festago/support/StageFixture.java
- backend/src/test/java/com/festago/support/TicketFixture.java
- backend/src/test/resources/application-test.yml
- backend/src/test/resources/application.yml
> [BE] feat: 축제 도메인 추가 및 기존 도메인 수정 (#106)

- backend/src/main/java/com/festago/application/FestivalService.java
- backend/src/main/java/com/festago/domain/Festival.java
- backend/src/main/java/com/festago/dto/FestivalCreateRequest.java
- backend/src/main/java/com/festago/dto/FestivalResponse.java
- backend/src/main/java/com/festago/presentation/AdminController.java
- backend/src/test/java/com/festago/application/FestivalServiceTest.java
- backend/src/test/java/com/festago/dto/FestivalCreateRequestTest.java
- backend/src/test/java/com/festago/presentation/AdminControllerTest.java
> [BE] feat: 축제 도메인 추가 및 기존 도메인 수정 (#115)

- backend/src/main/java/com/festago/domain/Ticket.java
- backend/src/test/java/com/festago/domain/TicketTest.java
> [BE] fix: 티켓의 입장시간과 요청시간이 일치하는 경우 입장이 불가한 버그 수정 (#136)

- backend/src/test/java/com/festago/domain/TicketTest.java
> [BE] feat: TicketTest 테스트 실패 케이스 수정 (#144)

- backend/src/main/java/com/festago/dto/ErrorResponse.java
- backend/src/test/java/com/festago/presentation/AdminControllerTest.java
> [BE] feat: ErrorResponse 클래스 Record로 변경 (#142)

- backend/src/main/java/com/festago/domain/Ticket.java
- backend/src/main/java/com/festago/exception/ErrorCode.java
- backend/src/test/java/com/festago/domain/TicketTest.java
> [BE] feat: Ticket 도메인에 예매한 수량 필드 추가 (#141)

- backend/src/test/java/com/festago/application/integration/ApplicationIntegrationTest.java
- backend/src/test/java/com/festago/application/integration/FestivalServiceIntegrationTest.java
- backend/src/test/java/com/festago/application/integration/StageServiceIntegrationTest.java
- backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
- closed: #139 
통합 테스트로 작성되었던 Service 테스트를 Integration 패키지로 분리하고, 네이밍에 Integration을 추가했습니다.
> [BE] feat: Service 레이어 통합 테스트 분리 (#139)

- backend/src/main/java/com/festago/application/TicketService.java
- backend/src/main/java/com/festago/domain/Ticket.java
- backend/src/main/java/com/festago/domain/TicketAmount.java
- backend/src/main/java/com/festago/domain/TicketAmountRepository.java
- backend/src/main/java/com/festago/domain/TicketEntryTime.java
- backend/src/main/java/com/festago/dto/TicketingRequest.java
- backend/src/main/java/com/festago/dto/TicketingResponse.java
- backend/src/main/java/com/festago/exception/ErrorCode.java
- backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
- backend/src/test/resources/ticketing-test-data.sql
> [BE] feat: 티켓 예매 API 구현 (#120)

- .gitmodules
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application.yml
- backend/src/test/resources/application-test.yml
> [ALL] 설정 파일 submodule로 관리 (#181)

- android/festago-staff/app/src/main/java/com/festago/festagostaff/data/service/TicketRetrofitService.kt
- closed: #178
스태프앱 api 변경사항 반영
> [AN/STAFF] feat: 티켓 확인 api 변동 사항 반영(#178)

- backend/src/main/resources/static/admin.js
- backend/src/main/resources/templates/admin.html
> [BE] fix: 티켓 생성 요청의 개수 필드 이름 수정 (#185)

- backend/src/main/java/com/festago/dto/FestivalDetailStageResponse.java
> [BE] faet: 축제 조회 DTO의 공연의 시작 시간 필드 이름 수정 (#187)

- backend/src/main/java/com/festago/presentation/MemberTicketController.java
- backend/src/test/java/com/festago/presentation/MemberTicketControllerTest.java
> [BE] feat: 티켓 예매 Api 구현 (#198)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
- android/festago/app/src/main/res/layout/fragment_ticket_reserve_bottom_sheet.xml
- android/festago/app/src/main/res/layout/item_ticket_reserve.xml
- android/festago/app/src/main/res/values/style.xml
- closed: #196
티켓 예매 페이지 버튼 마진 변경
바텀 시트 스타일 적용
> [AN/USER] 디자인 세부 내용 수정 (#196)

- android/festago/app/build.gradle.kts
- android/festago/build.gradle.kts
- closed: #208
- 유저 전용 앱 Crashlytics 기능 추가
> [AN/USER] 유저 전용 앱 Crashlytics 기능 추가 (#208)

- backend/src/main/java/com/festago/dto/MemberTicketResponse.java
- closed: #213
entryState를 state로 수정했습니다.
> [BE] refactor: 멤버티켓 조회 응답 DTO 네이밍 수정 (#213)

- backend/src/main/resources/application.yml
> [BE] chore: 서브모듈 업데이트 (#206)

- backend/src/main/java/com/festago/application/AdminService.java
- backend/src/main/java/com/festago/dto/AdminFestivalResponse.java
- backend/src/main/java/com/festago/dto/AdminResponse.java
- backend/src/main/java/com/festago/dto/AdminStageResponse.java
- backend/src/main/java/com/festago/dto/AdminTicketResponse.java
- backend/src/main/java/com/festago/presentation/AdminController.java
- backend/src/main/resources/static/admin.js
- backend/src/main/resources/static/style.css
- backend/src/main/resources/templates/admin.html
- backend/src/test/java/com/festago/presentation/AdminControllerTest.java
> [BE] feat: 어드민 페이지에 현재 존재하는 축제, 공연, 티켓의 정보를 포함한다 (#190)

- backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
> [BE] feat: info log 는 stack trace 를 포함하지 않는다 (#216)

- android/festago/app/src/main/java/com/festago/festago/data/repository/FestivalDefaultRepository.kt
- android/festago/app/src/main/java/com/festago/festago/data/repository/ReservationDefaultRepository.kt
- android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
- closed: #212
- 레트로핏 에러 처리시 Result.failure로 래핑
- 확장함수로 코드를 줄이려고 했으나 toDomain() 이슈로 보류합니다.
> [AN/USER] 유저 어플 레트로핏 에러처리 (#212)

- android/festago/app/src/main/java/com/festago/festago/data/dto/MemberTicketResponse.kt
- android/festago/app/src/main/java/com/festago/festago/data/service/TicketRetrofitService.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
- closed: #203 
member-ticket/current 적용
티켓 목록 새로고침
> [AN/USER] feat: 티켓 목록 API 수정 및 새로고침 (#203)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModel.kt
- android/festago/app/src/main/res/layout/fragment_ticket_list.xml
- android/festago/app/src/main/res/layout/item_ticket_list.xml
- closed: #227 
티켓 목록 새로고침
티켓 목록 화면 디자인 예정
> [AN/USER] feat: 티켓 목록 새로고침(#227)

- backend/src/main/resources/logback-spring.xml
- backend/src/main/resources/logs/common/file-error-appender.xml
- backend/src/main/resources/logs/common/file-info-appender.xml
- backend/src/main/resources/logs/common/file-warn-appender.xml
> [BE] chore: common log 롤링 적용 및 local 환경 console logging (#225)

- android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservationStageMapper.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/model/ReservationStageUiModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveViewHolder.kt
> [AN/USER] fix: 티켓 예매 새로고침 수정 (#234)

- backend/src/test/java/com/festago/domain/MemberTicketTest.java
- closed: #240 
실패하는 입장 가능 여부 검사 테스트를 수정했습니다.
> [BE] fix: 실패하는 입장 가능 여부 검사 테스트 수정 (#240)

- .gitignore
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/console-appender.xml
- backend/src/main/resources/logback-spring.xml
- backend/src/main/resources/logs/common/file-error-appender.xml
- backend/src/main/resources/logs/common/file-info-appender.xml
- backend/src/main/resources/logs/common/file-warn-appender.xml
- backend/src/main/resources/logs/error/file-error-appender.xml
- backend/src/main/resources/logs/error/file-info-appender.xml
- backend/src/main/resources/logs/error/file-warn-appender.xml
> [BE] chore: 로그 파일 저장 위치를 실행 환경 별로 분리한다 (#242)

- android/festago/app/build.gradle.kts
- android/festago/app/proguard-rules.pro
- android/festago/app/src/main/AndroidManifest.xml
- android/festago/app/src/main/java/com/festago/festago/FestagoApplication.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/util/UserApiClientExt.kt
- android/festago/settings.gradle.kts
- closed: #200 
카카오 로그인 세팅
몹 프로그래밍
> [AN/USER] feat: 카카오 로그인 기본 세팅 (#200)

- backend/src/main/java/com/festago/domain/MemberTicket.java
> [BE] refactor: EnumType String 변경 (#249)

- android/festago/app/src/main/java/com/festago/festago/data/RetrofitClient.kt
- android/festago/app/src/main/java/com/festago/festago/data/dto/UserProfileResponse.kt
- android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
- android/festago/app/src/main/java/com/festago/festago/data/repository/UserDefaultRepository.kt
- android/festago/app/src/main/java/com/festago/festago/data/service/TicketRetrofitService.kt
- android/festago/app/src/main/java/com/festago/festago/data/service/UserRetrofitService.kt
- android/festago/app/src/main/java/com/festago/festago/domain/model/UserProfile.kt
- android/festago/app/src/main/java/com/festago/festago/domain/repository/TicketRepository.kt
- android/festago/app/src/main/java/com/festago/festago/domain/repository/UserRepository.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/mapper/UserProfileMapper.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/model/StageUiModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketUiModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/model/UserProfileUiModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/BindingAdapter.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageEvent.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageUiState.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModel.kt
- android/festago/app/src/main/res/layout/fragment_my_page.xml
- android/festago/app/src/main/res/values/strings.xml
- android/festago/app/src/main/res/values/style.xml
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
- closed: #199 
- 로그인 후 마이페이지 구현했습니다.
**추후 작업 필요**
- (#277 작업 후) 
- 로그인 확인 후 로그인 페이지 이동 
- 요청 시 헤더에 토큰 추가
> [AN/USER] feat: 로그인 후 마이페이지 구현 (#199)

- backend/src/main/java/com/festago/auth/application/AuthService.java
- backend/src/main/java/com/festago/auth/dto/LoginResponse.java
- backend/src/test/java/com/festago/auth/application/AuthServiceTest.java
- backend/src/test/java/com/festago/auth/presentation/AuthControllerTest.java
> [BE] feat: 신규, 기존 회원 구분 기능 추가 (#179)

- backend/src/main/java/com/festago/domain/EntryCode.java
- backend/src/main/java/com/festago/exception/ErrorCode.java
- backend/src/test/java/com/festago/domain/EntryCodeTest.java
> [BE] feat: EntryCode의 offset에 검증 로직 추가 (#194)

- backend/src/main/java/com/festago/presentation/MemberController.java
- backend/src/test/java/com/festago/presentation/MemberControllerTest.java
> [BE] fix: 회원 프로필을 제대로 못받아오는 문제를 수정 (#299)

- android/festago/app/src/main/java/com/festago/festago/data/RetrofitClient.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
- closed: #304 
RetrofitClient 초기화 문제 수정
로그인 이벤트 후 홈 화면 이동 문제 수정
> [AN/USER] fix: 로그인 오류 수정 (#304)

- .github/workflows/ci-user-aos.yml
- android/festago/app/build.gradle.kts
- android/festago/app/src/main/AndroidManifest.xml
- android/festago/app/src/main/java/com/festago/festago/data/MockWeb.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketStateMapper.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/util/ParcelizeUtil.kt
- android/festago/app/src/test/java/com/festago/festago/data/repository/ReservationRetrofitServiceTest.kt
- android/festago/build.gradle.kts
- closed: #23
- ci-user-aos.yml 추가
- 빌드 실패하는 코드들 수정
- secrets key 추가
> [AN/USER] feat: PR시에 안드로이드 CI 적용 (#23)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
- android/festago/app/src/main/res/layout/fragment_ticket_list.xml
- android/festago/app/src/main/res/values/strings.xml
- closed: #314
티켓 목록 새로고침
티켓 목록 불러오기 오류 메세지 표시
> [AN/USER] feat: 티켓 목록 새로고침 해결 (#314)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeEvent.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeViewModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInViewModel.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/signin/SignInViewModelTest.kt
- closed: #317 
홈 화면에서 티켓 목록, 마이페이지 이동 시 토큰이 없으면 로그인 화면으로 이동
https://github.com/woowacourse-teams/2023-festa-go/assets/108349655/e30a074a-b72e-4046-a543-52d435bc1b8f
> [AN/USER] feat: 홈 화면에서 로그인하지 않은 경우 처리 (#317)

- android/festago/app/src/main/res/layout/activity_ticket_history.xml
- android/festago/app/src/main/res/layout/fragment_my_page.xml
- android/festago/app/src/main/res/layout/item_ticket_history.xml
> [AN/USER] feat: 예매 목록, 마이페이지의 티켓 카드뷰 수정 (#323)

- android/festago/app/src/main/java/com/festago/festago/data/dto/UserProfileResponse.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageEvent.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
- android/festago/app/src/main/res/layout/dialog_confirm_delete.xml
- android/festago/app/src/main/res/layout/fragment_my_page.xml
- android/festago/app/src/main/res/values/strings.xml
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModelTest.kt
- closed: #310 
- 마이페이지 회원 탈퇴 기능 연결
- 회원 탈퇴 시 AlertDialog 띄우기
- 프로필 이미지 null인 경우 처리
- 임시 로그아웃 제거
> [AN/USER] feat: 마이페이지 회원 탈퇴 기능(#310)

- android/festago/app/src/main/java/com/festago/festago/FestagoApplication.kt
- android/festago/app/src/main/java/com/festago/festago/data/repository/AuthDefaultRepository.kt
- android/festago/app/src/main/java/com/festago/festago/data/repository/FestivalDefaultRepository.kt
- android/festago/app/src/main/java/com/festago/festago/data/repository/ReservationTicketDefaultRepository.kt
- android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
- android/festago/app/src/main/java/com/festago/festago/data/repository/UserDefaultRepository.kt
- android/festago/app/src/main/java/com/festago/festago/data/retrofit/AuthInterceptor.kt
- android/festago/app/src/main/java/com/festago/festago/data/retrofit/AuthRetrofitClient.kt
- android/festago/app/src/main/java/com/festago/festago/data/util/ResponseExt.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInViewModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
- closed: #324
- 마이페이지 Auth 새로 고침 추가
- Auth 토큰 주입 방식 변경
- AuthRetoriftClient object로  변경
> [AN/USER] 유저 어플 Auth 토큰 만료 후 재발급 (#324)

- android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketMapper.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/model/MemberTicketUiModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListAdapter.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListItemViewHolder.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListUiState.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModel.kt
- android/festago/app/src/main/res/layout/item_ticket_list.xml
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
- closed: #337 
멤버 티켓 추가
목록 새로고침 반영
> [AN/USER] feat: 티켓 목록 새로고침 시 목록 업데이트 (#337) 

- android/festago/app/src/main/res/layout/fragment_my_page.xml
- closed: #341 
예매 티켓 목록 없을 때 보이지 않게 수정
> [AN/USER] feat: 예매 티켓 목록 없을 때 보이지 않게 수정(#341)

- backend/build.gradle
- backend/src/main/java/com/festago/exception/ErrorCode.java
- backend/src/main/java/com/festago/presentation/AdminController.java
- closed: #348 
/admin/error -> 에러 로그 발생
/admin/warn -> 경고 로그 발생
/admin/version -> 빌드 시간 확인
> [BE] feat: 어드민 컨트롤러에 디버깅용 핸들러 메서드 추가 (#348)

- backend/src/main/java/com/festago/auth/domain/OAuth2Clients.java
- closed: #311
Optional.ofNullable로 더 간단하게 풀어낼 수 있을 것 같아, Supplier를 활용하지 않는 방법으로 리팩토링해보았습니다!
혹시 제가 파악하지 못한 기존에 Supplier를 사용했던 추가적인 이유가 있으시면 말씀해주세요!
코드리뷰 부탁드려요!
> [BE] refactor: OAuth2Clients를 Supplier를 사용하지 않는 방식으로 리팩토링 (#311)

- android/festago/app/build.gradle.kts
> [AN/USER] chore: 앱 출시 버전 적용 (#346)

- backend/src/main/java/com/festago/domain/School.java
- backend/src/main/java/com/festago/domain/Student.java
> [BE] feat: School, Student 도메인 추가(#367)

- .github/workflows/cd-back-dev.yml
- .github/workflows/ci-back.yml
> [BE] feat: 백엔드 폴더의 변경 사항이 있을 때만 CD 수행 (#364)

- android/festago/app/build.gradle.kts
- android/festago/app/proguard-rules.pro
- closed: #378 
proguard-rules에 Glide, Retrofit 추가했습니다.
isMinifyEnabled, isShrinkResources true로 설정했습니다.
> [AN/USER] feat: 프로가드 난독화 수정(#378)

- android/festago/app/build.gradle.kts
- closed: #384
feat: 1.0.0 -> 1.0.1 버전 업
versionCode : 2 -> 3
> [AN/USER] feat: 1.0.1 버전 업(#384)

- backend/src/main/resources/static/css/404.css
- backend/src/main/resources/static/css/admin/admin-page.css
- backend/src/main/resources/static/css/admin/login.css
- backend/src/main/resources/static/error/404.html
- backend/src/main/resources/static/js/admin/admin-page.js
- backend/src/main/resources/static/js/admin/signup.js
- backend/src/main/resources/static/js/login.js
- backend/src/main/resources/templates/admin/admin-page.html
- backend/src/main/resources/templates/admin/login.html
- backend/src/main/resources/templates/admin/signup.html
> [BE] feat: 파일 리소스를 BOM 파일로 변경한다 (#386)

- backend/src/main/java/com/festago/auth/config/LoginConfig.java
- backend/src/main/java/com/festago/auth/domain/AuthPayload.java
- backend/src/test/java/com/festago/auth/infrastructure/JwtAuthExtractorTest.java
- backend/src/test/java/com/festago/auth/presentation/AuthControllerTest.java
> [BE] fix: 회원 탈퇴 Path에 Interceptor 적용 (#389) 

- backend/src/main/java/com/festago/auth/config/LoginConfig.java
- backend/src/main/java/com/festago/auth/domain/AuthPayload.java
- backend/src/test/java/com/festago/auth/infrastructure/JwtAuthExtractorTest.java
- backend/src/test/java/com/festago/auth/presentation/AuthControllerTest.java
> [BE] hot-fix: #389 핫픽스 dev 브랜치 적용 (#389)

- .github/workflows/assign-reviewer.yml
- .github/workflows/ci-back.yml
- .github/workflows/ci-user-aos.yml
- .github/workflows/closed-issue-notification.yml
- .github/workflows/closed-pr-notification.yml
- .github/workflows/opend-issue-notification.yml
- .github/workflows/opened-pr-notification.yml
> [ALL] feat: Github Action workflow 실행 조건에 main 브랜치 포함 (#392)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryUiState.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
- android/festago/app/src/main/res/layout/activity_ticket_entry.xml
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModelTest.kt
- closed: #405
- TicketUiModel 사용에서 Ticket으로 변경
> [AN] refactor: 예매 제시 화면 Presentation UiModel 제거 (#405)

- backend/src/main/java/com/festago/application/TicketingService.java
- backend/src/main/java/com/festago/domain/TicketRepository.java
- closed: #398 
fetch join 메소드를 추가하여 적용하였습니다.
> [BE] 티켓팅시 Lazy loading으로 인한 N+1문제를 개선 (#398)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/ReservationTicketArg.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveEvent.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveItemUiState.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/BottomSheetReservationTicketArg.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomItem.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
- closed: #418 
- TicketReservationUiModel -> 도메인 모델로 변경
- 바텀시트로 넘기는 모델은 ReservationTicketArg로 변경
> [AN/USER] refactor: TicketReserve 화면 presentation 모델 제거(#418)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListItemUiState.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListItemViewHolder.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModel.kt
- android/festago/app/src/main/res/layout/item_ticket_list.xml
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
- closed: #417 
티켓 목록 화면 presentation model 을 사용하지 않도록 변경
> [AN/USER] refactor: 티켓 목록 화면 presentation model 을 사용하지 않도록 변경

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
- closed: #423
- 예매 선택을 하지 않으면 버튼이 비활성화 하도록 수정
> [AN/USER] 예매 선택을 하지 않으면 버튼이 비활성화 하도록 수정 (#423)

- backend/src/main/java/com/festago/admin/domain/Admin.java
- backend/src/main/java/com/festago/auth/application/AuthService.java
- backend/src/main/java/com/festago/member/domain/Member.java
- backend/src/main/resources/db/migration/V3__unique_admin_social.sql
- backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
> [BE] feat: 동시 요청 시 발생할 수 있는 중복 회원 생성 문제 해결 (#443)

- backend/build.gradle
- backend/src/test/java/com/festago/acceptance/CucumberClient.java
- backend/src/test/java/com/festago/acceptance/CucumberSpringConfiguration.java
- backend/src/test/java/com/festago/acceptance/DataInitializer.java
- backend/src/test/java/com/festago/acceptance/EntryPoint.java
- backend/src/test/java/com/festago/acceptance/steps/ExampleStep.java
- backend/src/test/java/com/festago/acceptance/steps/ExampleStep2.java
- backend/src/test/resources/features/example.feature
- closed: #450 
디어디어 드디어 적용했습니다 관련 내용 정리글 다음과 같습니다.
[글](https://www.notion.so/wooteco-ash/Cucumber-with-JUnit5-12e0810362ca4bdb8088173f41b6ef86)
> [BE] feat: Cucumber 적용(#450)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolViewModel.kt
- closed: #473 
SelectSchoolUiState에 대한 확장함수, UiState 인터페이스의 확장함수, 캐스팅하는 범용 함수 등 다양한 시도가 있었지만 결국 기본 코드로 리턴..
> [AN/USER] refactor: 학교 선택 화면 success 캐스팅 코드 리팩(#473)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/util/LifecycleOwnerUtil.kt
> [AN/USER] LifecycleOwner 확장함수 리팩터링

- backend/src/main/resources/logback-spring.xml
> [BE] feat: 슬랙으로 오는 로그 알림에서 기본 WARN 알림 제외 (#485)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModel.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolViewModelTest.kt
- closed: #488 
- FestivalList, MyPage에 StateFlow / SharedFlow 적용했습니다.
- Turbine 테스트 반영했습니다.
- FestivalList, MyPage 뷰모델 테스트에서 중복된 given절 코드 리팩터링했습니다.
> [AN/USER] refactor: LiveData to Flow 리팩터링 (축제 목록, 마이페이지)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeViewModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
- closed: #490 
티켓 목록, 티켓 예매, 티켓 기록, 홈 화면 uiState 는 StateFlow 로 event 는 SharedFlow 로 리팩터링
테스트에 터빈 적용, LiveData 를 위한 Rule 제거
> [AN/USER] refactor: LiveData to Flow 리팩터링 (티켓 목록, 티켓 예매, 티켓 기록, 홈화면)

- backend/src/main/resources/db/migration/V7__studnet_code__unique.sql
> [BE] fix: sql 문법 에러 해결 (#500)

- backend/build.gradle
> [BE] chore: SpringBoot version 3.1.4로 업데이트

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInViewModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/signin/SignInViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModelTest.kt
- android/festago/domain/src/main/java/com/festago/festago/repository/TicketRepository.kt
- closed: #494 
- 티켓 제시 :  uiState를 combine을 이용해서 합쳐지도록 리팩터링
- 로그인 화면 :  SharedFlow로 리팩터링
- 테스트에 터빈 적용, LiveData 를 위한 Rule 제거
> [AN/USER] refactor: LiveData to Flow 리팩터링 (티켓 제시, 로그인 화면) (#494)

- android/festago/app/src/main/java/com/festago/festago/data/dto/ReservationStageResponse.kt
- android/festago/app/src/main/java/com/festago/festago/data/dto/ReservationTicketResponse.kt
- android/festago/app/src/main/java/com/festago/festago/data/dto/ReservationTicketsResponse.kt
- android/festago/app/src/main/java/com/festago/festago/data/repository/ReservationTicketDefaultRepository.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/BottomSheetReservationTicketArg.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/BottomSheetTicketTypeArg.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomViewHolder.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveViewHolder.kt
- android/festago/app/src/main/res/layout/item_ticket_reserve_bottom_sheet.xml
- android/festago/app/src/main/res/values/strings.xml
- android/festago/app/src/test/java/com/festago/festago/data/repository/ReservationTicketRetrofitServiceTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
- android/festago/domain/src/main/java/com/festago/festago/model/ReservationStage.kt
- android/festago/domain/src/main/java/com/festago/festago/model/ReservationTicket.kt
- android/festago/domain/src/main/java/com/festago/festago/model/ReservationTickets.kt
- android/festago/domain/src/main/java/com/festago/festago/model/TicketType.kt
- android/festago/domain/src/main/java/com/festago/festago/repository/ReservationTicketRepository.kt
- closed: #345 
재학생용 -> 방문객용 순으로 번역 완료
> [AN/USER] feat: 재학생, 방문객 영문 값 한글로 번역(#345)

- backend/src/main/resources/application.yml
- closed: #540 
infra 프로파일을 추가합니다.
> [BE] feat: application.yml infra 프로파일 추가(#540)

- backend/src/main/java/com/festago/student/infrastructure/MockMailClient.java
- closed: #548 
profile 바꿔서 작동하는 것도 확인한 후
infra, test ,local 에서 활성화 되도록 변경했습니다.
> [BE] feat: MockMailClient Profile 변경 (#548)

- android/festago/app/src/main/java/com/festago/festago/data/repository/SchoolDefaultRepository.kt
- closed: #550 
아이디에 맞는 학교 도메인을 찾아 불러온다
> [AN/USER] feat: 학생 인증 화면 학교 도메인 디폴트 값 제거 (#550)

- android/festago/app/src/main/res/layout/activity_select_school.xml
- android/festago/app/src/main/res/layout/activity_student_verification.xml
- android/festago/app/src/main/res/layout/item_select_school.xml
- android/festago/app/src/main/res/values/style.xml
> [AN/USER] fix: 학교 선택, 학교 인증 화면 다크모드 대응(#556)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
- android/festago/app/src/main/res/layout/fragment_ticket_reserve_bottom_sheet.xml
- android/festago/app/src/main/res/layout/item_ticket_reserve_header.xml
- android/festago/app/src/main/res/values/strings.xml
> [AN/USER] feat: 티켓 예매 디자인 수정 (#567)

- android/festago/app/build.gradle.kts
- closed: #571 
versionCode 5, versionName 1.1.1 변경
> [AN/USER] feat: 페스타고 유저 앱 버전 변경 (#571)

- android/festago/app/src/test/java/com/festago/festago/presentation/rule/MainDispatcherRule.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/signin/SignInViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewModelTest.kt
- android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
- closed: #589 
before, after 에서 처리해주던
테스트 디스페처 setMain, resetMain 를 TestRule 로 작성하였습니다.
```kotlin
@get:Rule
val mainDispatcherRule = MainDispatcherRule()
```
만 작성해주면 됩니다.
> [AN/USER] refactor: ViewModel Test Code Dispatcher Rule 추가

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationActivity.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
- android/festago/app/src/main/java/com/festago/festago/presentation/util/SingleClickUtil.kt
- android/festago/app/src/main/res/layout/fragment_ticket_reserve_bottom_sheet.xml
- android/festago/app/src/main/res/layout/item_ticket_reserve.xml
- closed: #584 
View.setOnSingleClickListener 로 view 의 클릭 이벤트를 설정할 수 있습니다.
bindingAdapter 를 사용해서 onSingleClick 으로 xml 파일에서 사용 가능합니다.
예매 화면의 예매하기 버튼, 티켓 선택 후 예매하기 버튼, 학생 인증 메일 전송 버튼에 사용했습니다.
> [AN/USER] feat: 버튼 더블 클릭 막기(#584)

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
- android/festago/app/src/main/res/values/strings.xml
- closed: #580 
홈 화면 뒤로가기 3초 내 두 번 클릭 시 종료된다
> [AN/USER] feat: 홈 화면에서 뒤로가기 누르면 곧바로 종료되지 않는다.

- android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
> [AN/USER] refactor: 네트워크 에러 로깅을 확장함수 없이 직접 처리한다(#595)

- backend/src/main/java/com/festago/ticket/application/TicketService.java
- backend/src/main/java/com/festago/ticket/repository/TicketRepository.java
- backend/src/test/java/com/festago/application/TicketServiceTest.java
- backend/src/test/java/com/festago/domain/TicketRepositoryTest.java
> [BE] refactor: /stages/{stageId}/tickets API의 N+1을 해결한다.(#517)

- backend/src/test/resources/application-test.yml
- closed: #605
테스트에서 불필요한 쿼리 로그를 없애서 속도를 개선합니다.
> [BE] test properties show sql 관련 설정 삭제 (#605)

- backend/src/main/java/com/festago/presentation/SchoolController.java
- closed: #597 
-- 변경 전
--- 변경 후
> [BE] 학교 정보 API에 Swagger Annotation을 추가 (#597)

- android/festago/app/build.gradle.kts
> [AN] release: v1.2.0 (#618)

- backend/src/main/java/com/festago/ticketing/application/MemberTicketService.java
- backend/src/main/java/com/festago/ticketing/dto/MemberTicketResponse.java
- backend/src/test/java/com/festago/ticketing/application/MemberTicketServiceTest.java
> [BE] refactor: MemberTicketService 로직을 개선한다. (#616)

- backend/build.gradle
- closed: #637
#637 이슈에 적은 내용 그대로 입니다.
추후 build.gradle 파일을 코틀린 문법을 사용하도록 변경해도 좋을 것 같네요.
[Gradle Kotlin DSL](https://blog.imqa.io/kotlin-dsl/)
> [BE] refactor: build.gradle QueryDSL 설정 개선 (#637)

- backend/src/main/java/com/festago/school/dto/SchoolCreateRequest.java
- backend/src/test/java/com/festago/school/intergration/SchoolServiceIntegration.java
- backend/src/test/java/com/festago/school/intergration/SchoolServiceIntegrationTest.java
- closed: #623
BEFROE
--- 
AFTER
---
> [BE] test: SchoolService의 통합테스트를 작성 (#623)

- .github/workflows/ci-back.yml
- closed: #662
이슈 내용과 같이 CI 스크립트의 대상 브랜치에 `feat/**` 패턴을 추가했습니다.
> [BE] feat: CI 스크립트 대상 브랜치 feat/** 추가 (#662)

- backend/src/main/java/com/festago/festival/presentation/v1/FestivalV1Controller.java
- backend/src/main/java/com/festago/festival/presentation/v1/PopularFestivalV1Controller.java
- closed: #683 
Swagger 어노테이션 추가했습니다
> [BE] feat: Swagger annotaion 추가 (#683)

- backend/src/main/java/com/festago/admin/application/AdminSchoolV1QueryService.java
- backend/src/main/java/com/festago/admin/dto/AdminSchoolV1Response.java
- backend/src/main/java/com/festago/admin/presentation/v1/AdminSchoolV1Controller.java
- backend/src/main/java/com/festago/admin/repository/AdminSchoolV1QueryDslRepository.java
- backend/src/test/java/com/festago/acceptance/steps/AdminSchoolStepDefinitions.java
- backend/src/test/java/com/festago/admin/application/integration/AdminSchoolV1QueryServiceIntegrationTest.java
- backend/src/test/java/com/festago/admin/presentation/v1/AdminSchoolV1ControllerTest.java
- closed: #738 
어제 이야기한 그대로 패키지만 옮겼습니다.
> [BE] Admin에서 사용되는 School CRUD 기능을 admin 패키지로 변경 (#738)

- backend/src/main/java/com/festago/common/exception/dto/ErrorResponse.java
- backend/src/main/java/com/festago/common/exception/dto/ValidErrorResponse.java
- backend/src/main/java/com/festago/common/handler/GlobalExceptionHandler.java
- backend/src/main/java/com/festago/config/WebConfig.java
- closed: #733
이슈 내용 그대로 Bean Validation을 개선했습니다.
적용한 이유에 대해서는 이슈에 자세히 나와있으니 참고 부탁드립니다!
기존 Request 클래스의 필드에 있는 Validation 어노테이션을 제거하는 것은 점진적으로 새로운 이슈로 작업하는게 좋을 듯 합니다.
> [BE] refactor: Bean Validation 메시지 개선 (#733)

- backend/src/main/java/com/festago/admin/domain/Admin.java
- backend/src/main/java/com/festago/admin/presentation/v1/AdminSchoolV1Controller.java
- backend/src/main/java/com/festago/common/util/Validator.java
- backend/src/main/java/com/festago/fcm/domain/MemberFCM.java
- backend/src/main/java/com/festago/festival/domain/Festival.java
- backend/src/main/java/com/festago/member/domain/Member.java
- backend/src/main/java/com/festago/school/domain/School.java
- backend/src/main/java/com/festago/student/domain/Student.java
- backend/src/main/java/com/festago/student/domain/StudentCode.java
- backend/src/main/java/com/festago/student/domain/VerificationCode.java
- backend/src/test/java/com/festago/common/util/ValidatorTest.java
- closed: #753
이슈 내용 그대로 말과 행동이 다른 `Validator` 클래스의 일부 메서드를 수정했습니다.
`Validator` 클래스는 도메인에 사용되는 클래스인 만큼, 의존도가 매우 높으니 충돌을 방지하기 위해 최대한 빠르게 머지하는게 좋을 것 같습니다.
> [BE] refactor: Validator hasBlank, isNegative 메서드 이름 변경 (#753)

- android/festago/presentation/src/main/res/layout/activity_home.xml
- closed: #766 
바텀 네비게이션 상단에 줄 추가
> [AN/USER] feat: 바텀 네비게이션 상단에 줄 추가(#766)

- android/festago/presentation/src/main/AndroidManifest.xml
- android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
- android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/notificationlist/NotificationListActivity.kt
- android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/notificationlist/NotificationListViewModel.kt
- android/festago/presentation/src/main/res/layout/activity_notification_list.xml
- android/festago/presentation/src/main/res/values/strings.xml
- closed: #771
1차 출시를 위해 알림 기능은 없지만 뷰만 만들었습니다.
> [AN/USER] feat: 알림 화면을 구현한다(#771)

- android/festago/data/src/main/java/com/festago/festago/data/di/singletonscope/ServiceModule.kt
- android/festago/data/src/main/java/com/festago/festago/data/dto/schooldetail/SchoolFestivalArtistResponse.kt
- android/festago/data/src/main/java/com/festago/festago/data/dto/schooldetail/SchoolFestivalResponse.kt
- android/festago/data/src/main/java/com/festago/festago/data/dto/schooldetail/SchoolFestivalsResponse.kt
- android/festago/data/src/main/java/com/festago/festago/data/dto/schooldetail/SchoolInfoResponse.kt
- android/festago/data/src/main/java/com/festago/festago/data/repository/FakeSchoolRepository.kt
- android/festago/data/src/main/java/com/festago/festago/data/repository/SchoolDefaultRepository.kt
- android/festago/data/src/main/java/com/festago/festago/data/service/SchoolRetrofitService.kt
- android/festago/domain/src/main/java/com/festago/festago/domain/repository/SchoolRepository.kt
- closed: #757 
- api 연동
- 명세 변경된 파라미터 반영
> [AN/USER] feat: 학교 상세 화면 API 연동 및 API 명세 변경 사항 반영 (#757)

- backend/build.gradle.kts
- closed: #865
Thymeleaf 의존을 제거했습니다.
> [BE] build: Thymeleaf 의존 제거 (#865)

- android/festago/data/src/main/java/com/festago/festago/data/repository/DefaultSearchRepository.kt
- android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailViewModel.kt
- android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/festival/ArtistDetailFestivalViewHolder.kt
- android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailFragment.kt
- android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListFestivalViewHolder.kt
- android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFestivalViewHolder.kt
- android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailViewModel.kt
- android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/festivalsearch/FestivalSearchViewHolder.kt
- android/festago/presentation/src/main/res/values/strings.xml
- closed: #900 
아티스트 상세, 학교 상세에서 이전 축제도 보여준다.
한글자 대학은 검색할 수 없다.
> [AN/USER] fix: 요구사항에 맞게 기능을 수정한다(#900)

- android/festago/app/build.gradle.kts
- android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/splash/SplashActivity.kt
- android/festago/presentation/src/main/res/layout/item_artist_detail_festival.xml
- android/festago/presentation/src/main/res/layout/item_festival_list_festival.xml
- android/festago/presentation/src/main/res/layout/item_school_detail_festival.xml
- android/festago/presentation/src/main/res/layout/item_search_festival.xml
- closed: #932
아티스트가 없으면 축제목록 아이템 높이가 줄어드는 문제가 있습니다.
이전 PR 에서 디자인 수정하다가 잘못건드렸습니다.
빠르게 반영하고 앱 버전 업 하겠습니다.
> [AN/USER] fix: 축제 목록 아이템 높이 수정(#932)

- android/festago/app/build.gradle.kts
- android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
- android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/bottomsheet/RegionBottomSheetDialogFragment.kt
> [AN/USER] fix: 축제 목록 지역 선택 crash 발생 해결(#958)

- backend/src/main/java/com/festago/school/application/SchoolCommandService.java
- backend/src/main/java/com/festago/school/domain/School.java
- backend/src/main/resources/db/migration/V4__remove_school_unique_domain.sql
- backend/src/test/java/com/festago/school/application/SchoolCommandServiceTest.java
- closed: #935
School domain의 유니크 제약 조건을 삭제했습니다.
> [BE] feat: School domain 유니크 제약조건 삭제 (#935)
